export const ATTENTION = {
  HYPERFOCUS_CURIOSITY: 0.75,
  HYPERFOCUS_ENERGY: 0.6,
  BLANK_ENERGY: 0.2,
  BLANK_GRAVITY: 0.7,
  DRIFT_BOREDOM: 0.6,
  DRIFT_ENERGY: 0.5,
  DRIFT_IDLE_TICKS: 3,
  DRIFT_INJECTION_PROBABILITY: 0.3,
  CONVERSATION_DRIFT_ENERGY: 0.3,
  CONVERSATION_DRIFT_BOREDOM: 0.65,
  CONVERSATION_DRIFT_MIN_MESSAGES: 15,
  FATIGUE_ONSET_TICKS: 12,
  FATIGUE_DRIFT_ENERGY: 0.5
} as const

export const METACOGNITION = {
  CLARITY_EMOTION_WEIGHT: 0.3,
  CLARITY_SOMA_WEIGHT: 0.2,
  CLARITY_FATIGUE_WEIGHT: 0.3,
  CLARITY_COHERENCE_WEIGHT: 0.2,
  RUMINATION_THRESHOLD_TICKS: 3,
  FATIGUE_PER_COMPLEX_DECISION: 0.1,
  FATIGUE_DECAY_PER_TICK: 0.95,
  FATIGUE_SLEEP_RESET: 0.3,
  MAX_RECENT_REASONINGS: 10,
  HEDGING_FATIGUE_THRESHOLD: 0.6,
  CONFIDENCE_MODIFIER_SCALE: 0.15
} as const

export const HABIT = {
  AUTOMATIC_STRENGTH_THRESHOLD: 0.8,
  DETECTION_MIN_REPETITIONS: 3,
  STRENGTH_INCREMENT: 0.1,
  DECAY_PER_TICK: 0.995,
  MAX_HABITS: 20,
  MAX_RECENT_ACTIVATIONS: 10
} as const

export const BOREDOM = {
  MIN_BOREDOM: 0.5,
  MIN_IDLE_TICKS: 2,
  BASE_PROBABILITY: 0.3,
  BOREDOM_SCALE: 0.4,
  IDLE_SCALE: 0.1,
  MAX_RECENT_IMPULSES: 10,
  ESCALATION_PERSONAL_TICKS: 5,
  ESCALATION_URGENT_TICKS: 10
} as const
