export const BIAS = {
  NEGATIVITY_WEIGHT: 2.5,
  AVAILABILITY_RECENCY_HOURS: 24,
  AVAILABILITY_BOOST: 0.3,
  ANCHORING_DECAY_RATE: 0.99,
  ANCHORING_MAX_POINTS: 10,
  MERE_EXPOSURE_THRESHOLD: 3,
  MERE_EXPOSURE_BOOST: 0.1,
  MERE_EXPOSURE_MAX: 0.5,
  OPTIMISM_BIAS_SCALE: 0.2,
  PEAK_END_WEIGHT: 0.7,
  CONFIRMATION_BELIEF_BOOST: 0.2,
  CORTISOL_NEGATIVITY_AMPLIFIER: 0.5,
  SEROTONIN_OPTIMISM_LINK: 0.3,
  DOPAMINE_CONFIRMATION_LINK: 0.2
} as const
