export const TYPING = {
  WORDS_PER_MINUTE: 50,
  BASE_THINKING_MS: 300,
  JITTER_FACTOR: 0.25,
  MIN_MS: 1500,
  MAX_MS: 20000,
  REFRESH_MS: 5000
} as const

export const CONVERSATION = {
  GAP_MINUTES: 30,
  MAX_ROUNDS: 10,
  MAX_BUFFER_SLOTS: 3,
  ARCHIVE_SUMMARY_MAX_TOKENS: 300,
  MAX_CLIMATE_THEMES: 5
} as const

export const THINKING = {
  INTER_PARAGRAPH_MIN_MS: 800,
  INTER_PARAGRAPH_MAX_MS: 2500,
  MIN_SPLIT_LENGTH: 200
} as const

export const MESSAGE_DELAY = {
  MIN_BETWEEN_MESSAGES_MS: 500,
  MAX_JITTER_MS: 1500
} as const

export const TYPOS = {
  CASUAL_PROBABILITY: 0.08,
  PLAYFUL_PROBABILITY: 0.12,
  TERSE_PROBABILITY: 0.05,
  ELABORATE_PROBABILITY: 0.02,
  RAW_PROBABILITY: 0.03,
  MIN_TEXT_LENGTH: 15,
  CORRECTION_DELAY_MIN_MS: 1000,
  CORRECTION_DELAY_MAX_MS: 3000,
  VULNERABILITY_BOOST: 0.3,
  EXCITEMENT_BOOST: 1.3,
  LOW_ENERGY_BOOST: 1.5,
  TENSION_FOCUS: 0.7,
  VULNERABILITY_OPEN_BOOST: 1.2
} as const

export const ACCUMULATION = {
  WINDOW_MS: 2500
} as const

export const PARAPRAXIS = {
  BASE_PROBABILITY: 0.03,
  PRESSURE_WEIGHT: 0.5,
  TENSION_WEIGHT: 0.3,
  CONFIDENCE_INVERSE_WEIGHT: 0.2,
  MIN_BUFFER_ENTRIES: 1,
  MIN_TEXT_LENGTH: 20,
  CORRECTION_DELAY_MIN_MS: 800,
  CORRECTION_DELAY_MAX_MS: 3000,
  STRIKETHROUGH_PROBABILITY: 0.35,
  PIVOT_PROBABILITY: 0.3,
  SUBSTITUTION_PROBABILITY: 0.35
} as const

export const REGISTER = {
  SWITCH_THRESHOLD: 0.15
} as const

export const MICRO_EXPRESSION = {
  TENSION_SENTENCE_SHORTENING: 0.6,
  FORMALITY_CAUTION_THRESHOLD: 0.6,
  FORMALITY_CONNECTION_CEILING: 0.4,
  REACTION_FORMATION_INTENSITY: 0.4,
  PUNCTUATION_FRUSTRATION_THRESHOLD: 0.5,
  ENERGY_COMPRESSION_THRESHOLD: 0.3
} as const
