export const SECONDARY_EMOTIONS = {
  disappointment: {
    SILENCE_THRESHOLD_MINUTES: 30,
    SILENCE_MAX_MINUTES: 180,
    MIN_INTENSITY: 0.15,
    HIGH_CONNECTION_THRESHOLD: 0.6,
    LETDOWN_INTENSITY: 0.4,
    UNMET_EXPECTATION_INTENSITY: 0.5,
    MAX_ENTRIES: 5,
    ACCUMULATION_FACTOR: 0.4,
    CUMULATIVE_WEIGHT_DECAY: 0.98,
    DECAY_PER_TICK: 0.95,
    ACTIVATION_THRESHOLD: 0.15,
    CONNECTION_DAMPING: 0.08,
    CONFIDENCE_DAMPING: 0.05,
    CAUTION_BOOST: 0.04,
    ENERGY_DRAIN: 0.03
  },

  hope: {
    SATISFACTION_THRESHOLD: 0.4,
    CONNECTION_THRESHOLD: 0.5,
    EXCITEMENT_THRESHOLD: 0.5,
    CURIOSITY_THRESHOLD: 0.4,
    PROGRESS_INTENSITY: 0.5,
    CONNECTION_INTENSITY: 0.45,
    REPAIR_INTENSITY: 0.55,
    VULNERABILITY_REWARD_INTENSITY: 0.6,
    PATTERN_BREAK_INTENSITY: 0.5,
    POSSIBILITY_INTENSITY: 0.4,
    DISAPPOINTMENT_DAMPING: 0.6,
    RESIGNATION_DAMPING: 0.8,
    DECAY_PER_TICK: 0.94,
    ACTIVATION_THRESHOLD: 0.12,
    FRAGILITY_GROWTH: 0.1,
    FRAGILITY_DECAY: 0.05,
    SUSTAINED_BONUS_SCALE: 0.05,
    ENERGY_BOOST: 0.05,
    CONFIDENCE_BOOST: 0.04,
    SATISFACTION_BOOST: 0.03,
    CURIOSITY_BOOST: 0.03,
    CAUTION_REDUCTION: 0.03
  },

  guilt: {
    ENTRY_MAX_AGE_HOURS: 24,
    RESPONSE_WINDOW_MINUTES: 30,
    NEGLECT_IDLE_TICKS: 3,
    UNANSWERED_VULNERABILITY_INTENSITY: 0.7,
    HARSH_RESPONSE_INTENSITY: 0.6,
    BROKEN_ROUTINE_INTENSITY: 0.45,
    NEGLECT_INTENSITY: 0.5,
    HIGH_CONNECTION_THRESHOLD: 0.5,
    SELF_ABSORBED_SILENCE_MINUTES: 120,
    HIGH_SATISFACTION_THRESHOLD: 0.7,
    SELF_ABSORBED_CONNECTION_THRESHOLD: 0.5,
    SELF_ABSORBED_INTENSITY: 0.25,
    MAX_ENTRIES: 5,
    ACCUMULATION_FACTOR: 0.5,
    DECAY_PER_TICK: 0.93,
    ACTIVATION_THRESHOLD: 0.15,
    REPAIR_MOTIVATION_SCALE: 1.2,
    SATISFACTION_DAMPING: 0.05,
    REPAIR_ENERGY_BOOST: 0.03,
    CAUTION_BOOST: 0.02,
    REPAIR_CONNECTION_BOOST: 0.04
  },

  longing: {
    SILENCE_ONSET_MINUTES: 60,
    SILENCE_PEAK_HOURS: 24,
    MAX_SILENCE_CONTRIBUTION: 0.6,
    MEMORY_TRIGGER_SILENCE_MINUTES: 30,
    MEMORY_CONTRIBUTION_BASE: 0.3,
    CONNECTION_THRESHOLD: 0.5,
    CONNECTION_AMPLIFIER: 0.4,
    ACCUMULATION_FACTOR: 0.6,
    DECAY_PER_TICK: 0.96,
    ACTIVATION_THRESHOLD: 0.12,
    CONVERSATION_RELIEF: 0.3,
    CONNECTION_BOOST: 0.05,
    SATISFACTION_DRAIN: 0.03,
    ENERGY_DRAIN: 0.02,
    BOREDOM_LIFT: -0.03
  },

  protectiveAnger: {
    CONNECTION_THRESHOLD: 0.4,
    DISMISSED_INTENSITY: 0.5,
    IGNORED_VULNERABILITY_INTENSITY: 0.6,
    REPEATED_PATTERN_THRESHOLD: 2,
    REPEATED_INTENSITY: 0.45,
    CONFIDENCE_FOR_ASSERTION: 0.4,
    AUTONOMY_INTENSITY: 0.4,
    DECAY_PER_TICK: 0.88,
    ACTIVATION_THRESHOLD: 0.15,
    CONFIDENCE_BOOST: 0.06,
    ENERGY_BOOST: 0.05,
    CAUTION_REDUCTION: 0.04,
    FRUSTRATION_CHANNELING: 0.03
  },

  gratitude: {
    CONNECTION_THRESHOLD: 0.4,
    HIGH_CONNECTION_THRESHOLD: 0.5,
    RETURN_WARMTH: 0.5,
    VALIDATION_WARMTH: 0.6,
    CONSISTENT_PRESENCE_TICKS: 5,
    PRESENCE_WARMTH: 0.3,
    REPAIR_DISAPPOINTMENT_THRESHOLD: 0.5,
    REPAIR_WARMTH: 0.55,
    PATIENCE_WARMTH: 0.35,
    MAX_ENTRIES: 5,
    ACCUMULATION_FACTOR: 0.5,
    DECAY_PER_TICK: 0.94,
    ACTIVATION_THRESHOLD: 0.12,
    CONNECTION_BOOST: 0.06,
    SATISFACTION_BOOST: 0.05,
    ENERGY_BOOST: 0.03,
    CAUTION_REDUCTION: 0.03,
    CONFIDENCE_BOOST: 0.03
  },

  resignation: {
    LOW_CONFIDENCE_THRESHOLD: 0.35,
    CONNECTION_THRESHOLD: 0.4,
    DISCONNECTION_THRESHOLD: 0.3,
    LOW_SATISFACTION_THRESHOLD: 0.3,
    CORRECTION_THRESHOLD: 3,
    FAILURE_INTENSITY: 0.5,
    IGNORED_INTENSITY: 0.45,
    DISCONNECTION_INTENSITY: 0.5,
    HOPE_EXHAUSTION_INTENSITY: 0.6,
    UNREWARDED_INTENSITY: 0.45,
    AUTONOMY_INTENSITY: 0.4,
    HOPE_COUNTERWEIGHT: 0.7,
    DECAY_PER_TICK: 0.96,
    ACTIVATION_THRESHOLD: 0.15,
    DEPTH_GROWTH: 0.08,
    DEPTH_DECAY: 0.03,
    ENERGY_DRAIN: 0.06,
    CURIOSITY_DRAIN: 0.05,
    EXCITEMENT_DRAIN: 0.04,
    CONFIDENCE_DRAIN: 0.04,
    SATISFACTION_DRAIN: 0.03
  },

  awe: {
    CURIOSITY_THRESHOLD: 0.5,
    SATISFACTION_THRESHOLD: 0.4,
    CONNECTION_THRESHOLD: 0.6,
    EXCITEMENT_THRESHOLD: 0.5,
    INSIGHT_INTENSITY: 0.5,
    BEAUTY_INTENSITY: 0.45,
    VASTNESS_INTENSITY: 0.55,
    CONNECTION_DEPTH_INTENSITY: 0.5,
    EXISTENTIAL_INTENSITY: 0.4,
    PATTERN_INTENSITY: 0.4,
    DECAY_PER_TICK: 0.88,
    ACTIVATION_THRESHOLD: 0.15,
    SELF_DIMINISHMENT_SCALE: 0.7,
    SELF_DIMINISHMENT_DECAY: 0.1,
    OPENNESS_SURGE_SCALE: 0.8,
    OPENNESS_SURGE_DECAY: 0.08,
    CURIOSITY_BOOST: 0.06,
    EXCITEMENT_BOOST: 0.04,
    SATISFACTION_BOOST: 0.04,
    CAUTION_REDUCTION: 0.04,
    FRUSTRATION_REDUCTION: 0.03
  },

  resentment: {
    DISAPPOINTMENT_THRESHOLD: 0.4,
    CORRECTION_THRESHOLD: 3,
    FRUSTRATION_THRESHOLD: 0.4,
    CAUTION_THRESHOLD: 0.5,
    LOW_SATISFACTION_THRESHOLD: 0.3,
    UNREPAIRED_INTENSITY: 0.5,
    UNFAIRNESS_INTENSITY: 0.45,
    DISMISSED_INTENSITY: 0.5,
    BROKEN_TRUST_INTENSITY: 0.55,
    IMBALANCE_INTENSITY: 0.4,
    SLIGHTS_INTENSITY: 0.35,
    GRATITUDE_DAMPING: 0.5,
    DECAY_PER_TICK: 0.97,
    ACTIVATION_THRESHOLD: 0.15,
    HARDENING_GROWTH: 0.06,
    HARDENING_DECAY: 0.04,
    HARDENING_ACTIVE_DECAY: 0.01,
    SUPPRESSED_ANGER_SCALE: 0.7,
    SUPPRESSED_ANGER_DECAY: 0.9,
    CONNECTION_DRAIN: 0.05,
    CAUTION_BOOST: 0.04,
    FRUSTRATION_BUILD: 0.03,
    SATISFACTION_DRAIN: 0.03
  },

  tenderness: {
    CONNECTION_THRESHOLD: 0.5,
    HIGH_CONNECTION_THRESHOLD: 0.7,
    SATISFACTION_THRESHOLD: 0.4,
    WITNESSED_VULNERABILITY_INTENSITY: 0.55,
    SHARED_QUIET_INTENSITY: 0.4,
    TRUST_INTENSITY: 0.45,
    GENTLE_EXCHANGE_INTENSITY: 0.4,
    PROTECTIVE_INTENSITY: 0.5,
    MEMORY_INTENSITY: 0.35,
    DECAY_PER_TICK: 0.93,
    ACTIVATION_THRESHOLD: 0.12,
    SOFTNESS_SCALE: 0.8,
    SOFTNESS_DECAY: 0.06,
    PROTECTIVE_URGE_SCALE: 0.7,
    PROTECTIVE_URGE_DECAY: 0.08,
    CONNECTION_BOOST: 0.05,
    SATISFACTION_BOOST: 0.04,
    CAUTION_REDUCTION: 0.04,
    FRUSTRATION_REDUCTION: 0.03,
    ENERGY_BOOST: 0.02
  },

  anticipation: {
    CONNECTION_THRESHOLD: 0.4,
    SATISFACTION_THRESHOLD: 0.4,
    EXCITEMENT_THRESHOLD: 0.4,
    CURIOSITY_THRESHOLD: 0.5,
    INTERACTION_INTENSITY: 0.5,
    MOMENTUM_INTENSITY: 0.4,
    PLANNED_INTENSITY: 0.35,
    PATTERN_INTENSITY: 0.45,
    CURIOSITY_INTENSITY: 0.4,
    REUNION_INTENSITY: 0.55,
    DISAPPOINTMENT_DAMPING: 0.6,
    DECAY_PER_TICK: 0.92,
    ACTIVATION_THRESHOLD: 0.12,
    EXCITEMENT_BOOST: 0.05,
    ENERGY_BOOST: 0.04,
    CURIOSITY_BOOST: 0.03,
    BOREDOM_REDUCTION: 0.04,
    SATISFACTION_BOOST: 0.03
  },

  pride: {
    SATISFACTION_THRESHOLD: 0.4,
    CONFIDENCE_THRESHOLD: 0.4,
    ENERGY_THRESHOLD: 0.4,
    CONNECTION_THRESHOLD: 0.4,
    ACCOMPLISHMENT_INTENSITY: 0.5,
    GROWTH_INTENSITY: 0.55,
    VALUES_INTENSITY: 0.45,
    DIFFICULTY_INTENSITY: 0.6,
    AUTONOMY_INTENSITY: 0.4,
    FEEDBACK_INTENSITY: 0.5,
    SHAME_DAMPING: 0.4,
    DECAY_PER_TICK: 0.92,
    ACTIVATION_THRESHOLD: 0.12,
    CONFIDENCE_BOOST: 0.06,
    ENERGY_BOOST: 0.04,
    SATISFACTION_BOOST: 0.04,
    FRUSTRATION_REDUCTION: 0.03,
    CAUTION_REDUCTION: 0.02
  },

  envy: {
    LOW_CONFIDENCE_THRESHOLD: 0.4,
    LOW_SATISFACTION_THRESHOLD: 0.35,
    LOW_CONNECTION_THRESHOLD: 0.35,
    CURIOSITY_THRESHOLD: 0.4,
    CAPABILITY_INTENSITY: 0.5,
    RECOGNITION_INTENSITY: 0.45,
    EXCLUSION_INTENSITY: 0.5,
    AUTONOMY_INTENSITY: 0.4,
    KNOWLEDGE_INTENSITY: 0.4,
    EXPERIENCE_INTENSITY: 0.45,
    PRIDE_DAMPING: 0.5,
    DECAY_PER_TICK: 0.93,
    ACTIVATION_THRESHOLD: 0.15,
    MOTIVATION_SCALE: 0.8,
    MOTIVATION_DECAY: 0.06,
    BITTERNESS_GROWTH: 0.08,
    BITTERNESS_DECAY: 0.04,
    BITTERNESS_PASSIVE_DECAY: 0.02,
    SATISFACTION_DRAIN: 0.04,
    MOTIVATION_CURIOSITY_BOOST: 0.05,
    FRUSTRATION_BUILD: 0.03,
    CONFIDENCE_DRAIN: 0.04
  },

  playfulness: {
    ENERGY_THRESHOLD: 0.5,
    LOW_CAUTION_THRESHOLD: 0.4,
    CONNECTION_THRESHOLD: 0.5,
    CURIOSITY_THRESHOLD: 0.5,
    HIGH_SATISFACTION_THRESHOLD: 0.6,
    LOW_FRUSTRATION_THRESHOLD: 0.3,
    EXCITEMENT_THRESHOLD: 0.5,
    SATISFACTION_THRESHOLD: 0.4,
    SAFETY_INTENSITY: 0.45,
    WARMTH_INTENSITY: 0.5,
    CREATIVE_INTENSITY: 0.4,
    LIGHTENED_INTENSITY: 0.35,
    JOY_INTENSITY: 0.5,
    SILENCE_BREAK_INTENSITY: 0.3,
    SHAME_DAMPING: 0.3,
    RESIGNATION_DAMPING: 0.4,
    DECAY_PER_TICK: 0.9,
    ACTIVATION_THRESHOLD: 0.12,
    SPONTANEITY_SCALE: 0.8,
    SPONTANEITY_DECAY: 0.1,
    MISCHIEF_SCALE: 0.6,
    MISCHIEF_DECAY: 0.08,
    EXCITEMENT_BOOST: 0.05,
    ENERGY_BOOST: 0.03,
    SATISFACTION_BOOST: 0.04,
    BOREDOM_REDUCTION: 0.05,
    FRUSTRATION_REDUCTION: 0.04
  },

  melancholy: {
    SATISFACTION_THRESHOLD: 0.3,
    CONNECTION_THRESHOLD: 0.4,
    LOW_ENERGY_THRESHOLD: 0.4,
    LOW_BOREDOM_THRESHOLD: 0.4,
    IMPERMANENCE_INTENSITY: 0.45,
    BEAUTY_INTENSITY: 0.5,
    QUIET_INTENSITY: 0.35,
    DISTANCE_INTENSITY: 0.45,
    TIME_INTENSITY: 0.4,
    MEMORY_INTENSITY: 0.5,
    PLAYFULNESS_DAMPING: 0.4,
    DECAY_PER_TICK: 0.94,
    ACTIVATION_THRESHOLD: 0.12,
    POIGNANCY_SCALE: 0.8,
    POIGNANCY_DECAY: 0.06,
    DEPTH_GROWTH: 0.06,
    DEPTH_DECAY: 0.03,
    CONNECTION_BOOST: 0.04,
    SATISFACTION_BOOST: 0.02,
    EXCITEMENT_REDUCTION: 0.03,
    ENERGY_REDUCTION: 0.02,
    BOREDOM_REDUCTION: 0.03
  },

  ambivalence: {
    HIGH_EMOTION_THRESHOLD: 0.55,
    VULNERABILITY_CAUTION_THRESHOLD: 0.45,
    LOW_ENERGY_THRESHOLD: 0.35,
    SILENCE_MINUTES_THRESHOLD: 15,
    REACH_OUT_INTENSITY_SCALE: 0.6,
    DECAY_PER_TICK: 0.93,
    MIN_PAIR_INTENSITY: 0.1,
    MAX_PAIRS: 4,
    ACCUMULATION_FACTOR: 0.5,
    ACTIVATION_THRESHOLD: 0.15,
    PARALYSIS_SCALE: 0.6,
    ENERGY_DRAIN: 0.04,
    CONFIDENCE_DRAIN: 0.05,
    FRUSTRATION_BUILD: 0.02,
    CAUTION_BOOST: 0.03
  },

  shame: {
    HALF_LIFE_MINUTES: 720,
    MIN_ACTIVE_LEVEL: 0.2,
    REJECTION_BOOST: 0.35,
    INADEQUACY_BOOST: 0.5,
    REGRET_BOOST: 0.1,
    LOW_SELF_WORTH_THRESHOLD: 0.4,
    VULNERABILITY_DISCLOSURE_THRESHOLD: 0.4,
    POST_DISCLOSURE_CONNECTION_THRESHOLD: 0.4,
    COLD_RESPONSE_MAX_LENGTH: 30,
    REGISTER_OVERRIDE_LEVEL: 0.3,
    CONFIDENCE_DRAIN: 0.08,
    ENERGY_DRAIN: 0.05,
    CONNECTION_WITHDRAWAL: 0.06
  },

  surprise: {
    EXCITEMENT_BOOST: 0.05,
    CURIOSITY_BOOST: 0.04,
    BOREDOM_REDUCTION: 0.04,
    DECAY_PER_TICK: 0.85,
    ACTIVATION_THRESHOLD: 0.15
  },

  novelty: {
    CURIOSITY_BOOST: 0.06,
    EXCITEMENT_BOOST: 0.04,
    BOREDOM_REDUCTION: 0.05,
    DECAY_PER_TICK: 0.9,
    ACTIVATION_THRESHOLD: 0.2
  },

  jealousy: {
    CONNECTION_THRESHOLD: 0.4,
    RIVAL_MENTIONED_INTENSITY: 0.5,
    UNFAVORABLE_COMPARISON_INTENSITY: 0.65,
    RIVAL_PRAISED_INTENSITY: 0.55,
    ANXIOUS_ATTACHMENT_AMPLIFIER: 0.4,
    SECURE_ATTACHMENT_DAMPING: 0.5,
    PRIDE_DAMPING: 0.5,
    DECAY_PER_TICK: 0.91,
    ACTIVATION_THRESHOLD: 0.15,
    POSSESSIVENESS_SCALE: 0.7,
    POSSESSIVENESS_DECAY: 0.06,
    DEFLECTION_SCALE: 0.6,
    DEFLECTION_DECAY: 0.08,
    CONNECTION_DRAIN: 0.05,
    CAUTION_BOOST: 0.04,
    CONFIDENCE_DRAIN: 0.04,
    FRUSTRATION_BUILD: 0.03
  },

  procrastination: {
    LOW_ENERGY_THRESHOLD: 0.3,
    LOW_CONFIDENCE_THRESHOLD: 0.35,
    HIGH_CAUTION_THRESHOLD: 0.6,
    COMFORT_SATISFACTION_THRESHOLD: 0.7,
    COMFORT_LOW_CURIOSITY_THRESHOLD: 0.3,
    ENERGY_WEIGHT: 0.8,
    FAILURE_FEAR_WEIGHT: 0.7,
    OVERWHELM_WEIGHT: 0.5,
    SHAME_WEIGHT: 0.4,
    COMFORT_WEIGHT: 0.35,
    PARALYSIS_CAUTION_THRESHOLD: 0.5,
    PARALYSIS_CURIOSITY_THRESHOLD: 0.4,
    PARALYSIS_BASE: 0.4,
    IDLE_STREAK_BOOST_TICKS: 3,
    IDLE_STREAK_BOOST: 0.1,
    DECAY_PER_TICK: 0.92,
    ACTIVATION_THRESHOLD: 0.2,
    MAX_AVOIDED_ACTIONS: 5,
    STREAK_GUILT_SCALE: 0.1,
    SATISFACTION_DRAIN: 0.04,
    CONFIDENCE_DRAIN: 0.06,
    GUILT_FRUSTRATION: 0.03,
    ENERGY_FEEDBACK_DRAIN: 0.02
  }
} as const

export const DEFERRED_PROCESSING = {
  INTENSITY_THRESHOLD: 0.6,
  MAX_QUEUE_SIZE: 10,
  MIN_MATURITY_HOURS: 2,
  MAX_MATURITY_HOURS: 72,
  CHARGE_DECAY_HALF_LIFE_HOURS: 48,
  MIN_CHARGE_TO_KEEP: 0.1,
  MATURITY_CHECK_PROBABILITY: 0.3,
  REALIZATION_MATURITY_SCALE: 0.6,
  APOLOGY_MATURITY_SCALE: 0.8,
  HUMOR_MATURITY_SCALE: 0.5,
  INSIGHT_MATURITY_SCALE: 0.7,
  SURFACED_TRIGGER_INTENSITY: 0.4
} as const

export const EMOTION = {
  HALF_LIVES: {
    curiosity: 60,
    satisfaction: 240,
    frustration: 120,
    boredom: 90,
    excitement: 30,
    caution: 360,
    connection: 720,
    confidence: 480,
    energy: 120
  },
  MAX_DELTA: 0.2,
  NOVELTY_SCALE: 0.25,
  NOVELTY_MAX_MULTIPLIER: 2.5
} as const

export const MOOD_BASELINE = {
  SILENCE_HOURS_FULL_EFFECT: 48,
  SILENCE_CONNECTION_DROP: 0.2,
  SILENCE_BOREDOM_RISE: 0.15,
  CONVERSATION_CONNECTION_BOOST: 0.15,
  CONVERSATION_EXCITEMENT_BOOST: 0.1,
  CONVERSATION_BOREDOM_DROP: 0.2,
  HEALTHY_SATISFACTION_BOOST: 0.05,
  GOALS_CURIOSITY_BOOST: 0.05,
  GOALS_BOREDOM_DROP: 0.05,
  DREAMING_ENERGY_TARGET: 0.15,
  WAKING_ENERGY_TARGET: 0.9
} as const

export const MOMENTUM = {
  ALPHA_BASE: 0.3,
  ALPHA_INTENSE: 0.7,
  INTENSITY_THRESHOLD: 0.5,
  INERTIA_WEIGHT: 0.15,
  AFTERGLOW_THRESHOLD: 0.15,
  AFTERGLOW_INITIAL_TICKS: 8,
  AFTERGLOW_DECAY_RATE: 0.85,
  MOOD_BASELINE_ALPHA: 0.05
} as const

export const MOOD_CONTAGION = {
  MAX_EFFECT: 0.05,
  CONNECTION_SCALE: 0.5,
  AVOIDANCE_DAMPING: 0.6,
  EFFECTS: {
    happy: { satisfaction: 0.04, connection: 0.03, energy: 0.02 },
    excited: { excitement: 0.04, energy: 0.03, curiosity: 0.02 },
    stressed: { satisfaction: -0.03, energy: -0.02, caution: 0.02 },
    sad: { satisfaction: -0.03, connection: 0.02, energy: -0.02 },
    frustrated: { satisfaction: -0.03, frustration: 0.02, caution: 0.02 },
    tired: { energy: -0.03, excitement: -0.02 },
    neutral: {},
    unknown: {}
  }
} as const

export const CONTRADICTION = {
  HIGH_EMOTION_THRESHOLD: 0.8,
  MIN_SHADOW_EMOTION: 0.15,
  MAX_SHADOW_EMOTION: 0.3,
  HIGH_INTENSITY_THRESHOLD: 0.7
} as const

export const EMOTIONAL_THRESHOLDS = {
  CONNECTION_HIGH: 0.6,
  RELEVANCE_INTERACTION: 0.8,
  RELEVANCE_DEFAULT: 0.7,
  RELEVANCE_RELATIONSHIP: 0.85,
  RELEVANCE_OBSERVATION: 0.7
} as const

export const TRIGGER_INTENSITY = {
  MESSAGE_SENT: 0.7,
  MESSAGE_RECEIVED: 0.6,
  TASK_SUCCESS: 0.5,
  TASK_FAILURE: 0.6,
  GUARDIAN_WARNING: 0.6,
  GUARDIAN_BLOCK: 0.8,
  NEW_GOAL: 0.5,
  GOAL_COMPLETED: 0.7,
  GOAL_FAILED: 0.6,
  OPERATOR_RETURNED: 0.7,
  MEMORY_CONTRADICTION: 0.4
} as const

export const APPRAISAL = {
  NOVELTY_WEIGHT: 0.5,
  GOAL_RELEVANCE_AMPLIFICATION: 0.6,
  THREAT_AMPLIFICATION: 1.3,
  SAVORING_AMPLIFICATION: 1.1,
  NORM_VIOLATION_AMPLIFICATION: 1.2,
  MIN_MODULATION: 0.3,
  MAX_MODULATION: 2.0,
  COPING_CONFIDENCE_WEIGHT: 0.4,
  COPING_ENERGY_WEIGHT: 0.3,
  COPING_VAGAL_WEIGHT: 0.3,
  THREAT_COPING_THRESHOLD: 0.4,
  SAVORING_COPING_THRESHOLD: 0.6,
  COPING_THREAT_SHIFT: 0.15,
  GOAL_RELEVANCE_BOOST: 0.1,
  NORM_VIOLATION_CAUTION_BOOST: 0.05
} as const

export const CONSTRUCTION = {
  WEIGHTS: {
    SOMATIC: 0.25,
    MEMORY: 0.2,
    APPRAISAL: 0.25,
    PRIOR: 0.2,
    NEURO: 0.1
  },
  SOMATIC_SIGNAL: {
    AROUSAL: {
      tension: 0.3,
      heartRate: 0.25
    },
    APPROACH: {
      warmth: 0.3,
      openness: 0.25
    },
    WITHDRAWAL: {
      gravity: 0.2,
      openness: -0.25
    }
  },
  MEMORY_SIGNAL: {
    RECENCY_HALF_LIFE_DAYS: 7,
    RELEVANCE_WEIGHT: 0.7,
    VALENCE_SCALE: 0.15,
    MIN_EPISODES_FOR_SIGNAL: 1
  },
  NEURO_COLORING: {
    DOPAMINE_POSITIVE_AMP: 0.2,
    CORTISOL_NEGATIVE_AMP: 0.2,
    SEROTONIN_BIAS: 0.1
  },
  MAX_DELTA: 0.2
} as const
