export const BOUNDARIES = {
  DEFAULT_STRENGTH: 0.5,
  VIOLATION_HARDENING: 0.15,
  TRUST_SOFTENING_RATE: 0.02,
  PERMEABILITY_TRUST_WEIGHT: 0.4,
  PERMEABILITY_SECURITY_WEIGHT: 0.3,
  PERMEABILITY_VULNERABILITY_WEIGHT: 0.3,
  MAX_BOUNDARIES: 15,
  MAX_RECENT_VIOLATIONS: 10,
  FORMATION_NEGATIVE_THRESHOLD: 0.6
} as const
