export const DREAM_AFTERGLOW = {
  TTL_SECONDS: 14400,
  DECAY_PER_TICK: 0.9,
  BLEND_WEIGHT: 0.2,
  MIN_INTENSITY: 0.05
} as const

export const DREAM_PHASES = {
  NREM_RECONSOLIDATION_MULTIPLIER: 0.5,
  REM_RECONSOLIDATION_MULTIPLIER: 1.5
} as const
