export const COHERENCE = {
  REGRESSION_THRESHOLD: 0.25,
  REGRESSION_STRESS_THRESHOLD: 0.7,
  REGRESSION_DEPTH_INCREMENT: 0.1,
  COMMUNICATION_SIMPLIFICATION: 0.3,
  EMOTIONAL_DAMPING: 0.2,
  MISMATCH_WEIGHT: 0.2,
  RECOVERY_RATE: 0.05
} as const
