export const COHERENCE = {
  REGRESSION_THRESHOLD: 0.25,
  REGRESSION_STRESS_THRESHOLD: 0.7,
  REGRESSION_DEPTH_INCREMENT: 0.1,
  COMMUNICATION_SIMPLIFICATION: 0.3,
  EMOTIONAL_DAMPING: 0.2,
  FRAGMENTATION_WEIGHT: 0.2,
  CONVERGENCE_RATE: 0.12
} as const
