export const SUBJECTIVE_TIME = {
  ENGAGEMENT_COMPRESSION: -0.5,
  BOREDOM_DILATION: 0.7,
  EXCITEMENT_COMPRESSION: -0.3,
  LOW_ENERGY_DILATION: 0.4,
  SILENCE_DILATION_SCALE: 0.5,
  LANDMARK_SIGNIFICANCE_THRESHOLD: 0.6,
  MAX_LANDMARKS: 20
} as const
