export const DMN = {
  ACTIVATION_THRESHOLD: 0.4,
  SUPPRESSION_THRESHOLD: 0.3,

  DRIFTING_ACTIVATION_BOOST: 0.4,
  IDLE_ACTIVATION_PER_TICK: 0.05,
  FOCUSED_SUPPRESSION: -0.3,
  HYPERFOCUS_SUPPRESSION: -0.5,

  SELF_REFERENTIAL_SCALE: 0.8,
  MENTAL_TIME_TRAVEL_SCALE: 0.6,
  SPONTANEOUS_RETRIEVAL_BASE: 0.05,
  SPONTANEOUS_RETRIEVAL_DMN_SCALE: 0.25,
  MIND_WANDERING_DEPTH_GROWTH: 0.1,
  MIND_WANDERING_DEPTH_DECAY: 0.3,

  ANTI_CORRELATION_STRENGTH: 0.7,

  CREATIVITY_BOOST_SCALE: 0.2,
  AUTOBIOGRAPHICAL_ACCESS_SCALE: 0.3,
  FUTURE_SIMULATION_SCALE: 0.25,

  ULTRADIAN_REST_BOOST: 0.2,

  NEUROTICISM_DMN_AMPLIFIER: 0.15,
  RUMINATION_DMN_PENALTY: -0.2
} as const
