export const ANTICIPATION_SYSTEM = {
  MAX_EXPECTATIONS: 10,
  EXPECTATION_DECAY_PER_TICK: 0.95,
  VIOLATION_SURPRISE_SCALE: 0.8,
  VIOLATION_MEMORY_SIZE: 5,
  PATTERN_CONFIDENCE_THRESHOLD: 0.3,
  POSITIVE_ANTICIPATION_EXCITEMENT: 0.06,
  NEGATIVE_ANTICIPATION_CAUTION: 0.05,
  VIOLATION_POSITIVE_EXCITEMENT: 0.08,
  VIOLATION_NEGATIVE_FRUSTRATION: 0.06
} as const
