export const TRANSFERENCE = {
  MAX_TEMPLATES: 8,
  MIN_PATTERN_OCCURRENCES: 3,
  MATCH_THRESHOLD: 0.5,
  ACTIVATION_DECAY: 0.95,
  STRENGTH_INCREMENT: 0.05,
  STRENGTH_DECAY: 0.998,
  AWARENESS_LEARNING_RATE: 0.01,
  MAX_AWARENESS: 0.8,
  EMOTION_MODULATION_SCALE: 0.15,
  TEMPLATE_FORMATION_PROBABILITY: 0.05,
  ACTIVATION_CHECK_PROBABILITY: 0.3,
  AWARENESS_METACOGNITION_BOOST: 0.5,
  TEMPLATE_INITIAL_STRENGTH: 0.3,
  TEMPLATE_MIN_STRENGTH: 0.05,
  ACTIVATION_SIGNIFICANCE_THRESHOLD: 0.005,
  MATCH_MOOD_WEIGHT: 0.3,
  MATCH_TIME_WEIGHT: 0.1,
  MATCH_OVERLAP_WEIGHT: 0.1,
  MATCH_OVERLAP_MAX: 0.3,
  MATCH_TONE_WEIGHT: 0.2,
  MATCH_PATTERN_WEIGHT: 0.1,
  AWARENESS_DAMPENING_SCALE: 0.5,
  MOOD_EMOTION_MAPPINGS: {
    positive: { satisfaction: 0.1, connection: 0.08, excitement: 0.05 },
    negative: { frustration: 0.1, caution: 0.08, satisfaction: -0.05 },
    neutral: { curiosity: 0.03 },
    anxious: { caution: 0.12, confidence: -0.08, frustration: 0.05 },
    warm: { connection: 0.12, satisfaction: 0.08 },
    critical: { frustration: 0.1, confidence: -0.1, caution: 0.08 },
    distant: { connection: -0.1, caution: 0.06, boredom: 0.05 }
  } as Record<string, Record<string, number>>,
  MOOD_DEFAULT_EMOTION: { curiosity: 0.02 } as Record<string, number>
} as const
