export const RELATIONSHIP_PHASES = {
  DISCOVERING_INTERACTIONS: 50,
  DISCOVERING_DAYS: 7,
  HONEYMOON_MAX_INTERACTIONS: 200,
  HONEYMOON_CONNECTION: 0.6,
  HONEYMOON_MAX_CONFLICTS: 3,
  TENSIONS_MIN_CONFLICTS: 3,
  TENSIONS_CONNECTION: 0.5,
  DEEPENING_CONNECTION: 0.55,
  DEEPENING_TRUST: 0.5,
  COMFORTABLE_DAYS: 60,
  COMFORTABLE_SECURITY: 0.6,
  RENEWAL_CONNECTION_SPIKE: 0.7,
  MIN_PHASE_TICKS: 10
} as const

export const VULNERABILITY = {
  DISCLOSURE_THRESHOLD: 0.55,
  HESITATION_SCALE: 0.5,
  TYPO_VULNERABILITY_BOOST: 0.3
} as const
