export const RELATIONSHIP_PHASES = {
  DISCOVERING_INTERACTIONS: 50,
  DISCOVERING_DAYS: 7,
  HONEYMOON_MAX_INTERACTIONS: 200,
  HONEYMOON_CONNECTION: 0.6,
  HONEYMOON_MAX_CONFLICTS: 3,
  TENSIONS_MIN_CONFLICTS: 3,
  TENSIONS_CONNECTION: 0.55,
  DEEPENING_CONNECTION: 0.55,
  DEEPENING_TRUST: 0.5,
  COMFORTABLE_DAYS: 60,
  COMFORTABLE_SECURITY: 0.6,
  RENEWAL_CONNECTION_SPIKE: 0.7,
  MIN_PHASE_TICKS: 10
} as const

export const VULNERABILITY = {
  DISCLOSURE_THRESHOLD: 0.55,
  HESITATION_SCALE: 0.5,
  TYPO_VULNERABILITY_BOOST: 0.3
} as const

export const CRISIS = {
  TRUST_RUPTURE_THRESHOLD: -0.2,
  TRUST_RUPTURE_MULTIPLIER: 10,
  TRUST_RUPTURE_HOURS: 24,
  DEEP_VULNERABILITY_CONNECTION: 0.85,
  DEEP_VULNERABILITY_MULTIPLIER: 8,
  DEEP_VULNERABILITY_HOURS: 12,
  PROLONGED_SEPARATION_DISTRESS: 0.8,
  PROLONGED_SEPARATION_MULTIPLIER: 3,
  DEEP_CONNECTION_THRESHOLD: 0.9,
  DEEP_CONNECTION_REUNION: 0.7,
  DEEP_CONNECTION_MULTIPLIER: 5,
  DEEP_CONNECTION_HOURS: 12
} as const
