export const LIFECYCLE = {
  MIN_EVENT_HOURS: 1,
  MAX_EVENT_HOURS: 4,
  BURST_COOLDOWN_TICKS: 3,
  BURST_COOLDOWN_JITTER: 3,
  BURST_COOLDOWN_SKIP_BOOST: 0.3,
  DREAM_WINDOW_START: 0,
  DREAM_WINDOW_END: 5,
  DREAM_COOLDOWN_HOURS: 20,
  SLEEP_MIN_HOURS: 5,
  SLEEP_MAX_HOURS: 7,
  EVENT_COOLDOWN_HOURS: 8,
  EVENT_HISTORY_SIZE: 20,
  CONVERSATION_GUARD_MINUTES: 10
} as const
