export const CREATIVITY = {
  URGE_THRESHOLD: 0.6,
  EXPRESSION_DRIVE_WEIGHT: 0.4,
  EMOTION_PRESSURE_WEIGHT: 0.3,
  BOREDOM_WEIGHT: 0.2,
  HELD_BACK_WEIGHT: 0.1,
  SPONTANEOUS_THRESHOLD: 0.75,
  IDLE_TICKS_FOR_SPONTANEOUS: 3,
  DECAY_PER_TICK: 0.93
} as const
