export const EMOTION_REGULATION = {
  MAX_ACTIVE_STRATEGIES: 3,
  MAX_SUPPRESSION_TARGETS: 5,

  SUPPRESSION_DISTRESS_THRESHOLD: 0.6,
  ATTRIBUTION_BIAS_INSECURITY_THRESHOLD: 0.5,
  REAPPRAISAL_DISSONANCE_THRESHOLD: 0.4,
  BEHAVIORAL_ACTIVATION_DRIVE_FRUSTRATION_THRESHOLD: 0.6,
  BEHAVIORAL_ACTIVATION_MIN_ENERGY: 0.4,
  BEHAVIORAL_ACTIVATION_MIN_BLOCKED_TICKS: 3,
  EXPRESSIVE_SUPPRESSION_SHAME_THRESHOLD: 0.5,
  EXPRESSIVE_SUPPRESSION_MAX_ENERGY: 0.25,
  DISTANCING_VULNERABILITY_THRESHOLD: 0.5,
  DISTANCING_MIN_CAUTION: 0.5,
  SELECTIVE_ATTENTION_SELF_CONCEPT_THREAT_THRESHOLD: 0.6,
  SITUATION_MODIFICATION_FRUSTRATION_THRESHOLD: 0.5,

  AUTHENTICITY_DAMPENING: 0.5,
  VULNERABILITY_BYPASS: 0.7,
  CORTISOL_AMPLIFIER: 0.3,

  SUPPRESSION_RELEVANCE_REDUCTION: 0.4,
  SUPPRESSION_DECAY_PER_DAY: 0.02,

  DREAM_BREAKTHROUGH_PROBABILITY: 0.15,
  REFLECTION_BREAKTHROUGH_PROBABILITY: 0.1,
  VULNERABILITY_BREAKTHROUGH_PROBABILITY: 0.2,

  STRATEGY_DECAY_HALF_LIFE_HOURS: 12,
  MIN_STRATEGY_INTENSITY: 0.05,

  OPPORTUNITY_COST_THRESHOLD: 0.6,
  STRATEGY_PRIORITY_WEIGHTS: {
    suppression: 0.9,
    attribution_bias: 0.5,
    reappraisal: 0.7,
    behavioral_activation: 0.4,
    expressive_suppression: 0.85,
    distancing: 0.5,
    selective_attention: 0.6,
    situation_modification: 0.3
  } as Record<string, number>
} as const
