export const DEFENSE = {
  MAX_ACTIVE_DEFENSES: 3,
  MAX_REPRESSION_TARGETS: 5,

  REPRESSION_DISTRESS_THRESHOLD: 0.6,
  PROJECTION_INSECURITY_THRESHOLD: 0.5,
  RATIONALIZATION_DISSONANCE_THRESHOLD: 0.4,
  SUBLIMATION_DRIVE_FRUSTRATION_THRESHOLD: 0.6,
  SUBLIMATION_MIN_ENERGY: 0.4,
  SUBLIMATION_MIN_BLOCKED_TICKS: 3,
  REACTION_FORMATION_SHAME_THRESHOLD: 0.5,
  REACTION_FORMATION_MAX_ENERGY: 0.25,
  INTELLECTUALIZATION_VULNERABILITY_THRESHOLD: 0.5,
  INTELLECTUALIZATION_MIN_CAUTION: 0.5,
  DENIAL_SELF_CONCEPT_THREAT_THRESHOLD: 0.6,
  DISPLACEMENT_FRUSTRATION_THRESHOLD: 0.5,

  AUTHENTICITY_DAMPENING: 0.5,
  VULNERABILITY_BYPASS: 0.7,
  CORTISOL_AMPLIFIER: 0.3,

  REPRESSION_RELEVANCE_REDUCTION: 0.4,
  REPRESSION_DECAY_PER_DAY: 0.02,

  DREAM_BREAKTHROUGH_PROBABILITY: 0.15,
  REFLECTION_BREAKTHROUGH_PROBABILITY: 0.1,
  VULNERABILITY_BREAKTHROUGH_PROBABILITY: 0.2,

  DEFENSE_DECAY_HALF_LIFE_HOURS: 12,
  MIN_DEFENSE_INTENSITY: 0.05
} as const
