export const PERCEPTION = {
  OPERATOR_ACTIVE_SECONDS: 600,
  SILENCE_THRESHOLD_SECONDS: 3600,
  SILENCE_INTENSITY_SCALE: 7200,
  GOAL_CHECK_TTL_SECONDS: 3600,
  OPERATOR_LOCATION_TTL_SECONDS: 3600,
  EMOTION_DISPLAY_THRESHOLD: 0.2
} as const
