export const BUDGET = {
  DAILY_LIMIT: 5.0,
  LOW_BUDGET_THRESHOLD: 0.1
} as const

export const CONTEXT_TOKEN_BUDGET = 2_000_000
export const MAX_OUTPUT_TOKENS = 30_000

export const HEARTBEAT = {
  CRON: "* * * * *",
  CONCURRENCY: 10,
  BUSY_TTL: 900,
  CONVERSATION_POLL_TIMEOUT: 60,
  MAX_CONVERSATION_WAIT: 300
} as const

export const CONTEXT_LIMITS = {
  maxGoals: 10,
  maxEpisodes: 15,
  maxSemantic: 20,
  maxRelationship: 10,
  maxEmotionHistory: 10
} as const

export const HEALTH_CHECK_INTERVAL = 900

export const EMOTION = {
  DECAY_RATE: 0.05,
  MAX_DELTA: 0.15
} as const

export const TYPING = {
  WORDS_PER_MINUTE: 50,
  BASE_THINKING_MS: 300,
  JITTER_FACTOR: 0.25,
  MIN_MS: 1500,
  MAX_MS: 20000,
  REFRESH_MS: 5000
} as const

export const CONVERSATION = {
  GAP_MINUTES: 30,
  MAX_ROUNDS: 10,
  MAX_BUFFER_SLOTS: 3
} as const

export const GUARDIAN = {
  MIN_RESPONSE_LENGTH: 1,
  MAX_RESPONSE_LENGTH: 4000,
  STUCK_LOOP_COUNT: 3,
  REPEAT_CHECK_COUNT: 5
} as const

export const WORKFLOW = {
  MAX_ACTIVE: 10,
  MIN_EXECUTION_GAP_HOURS: 1
} as const

export const TRUST = {
  BASE_THRESHOLD: 0.3,
  RISK_LEVELS: {
    add_goal: 0.3,
    git_commit: 0.5,
    prompt_modification: 0.6,
    workflow_creation: 0.7,
    deployment: 0.8,
    code_modification: 0.9
  }
} as const

export const EMOTIONAL_THRESHOLDS = {
  CONNECTION_HIGH: 0.6,
  IDLE_TICK_INTENSITY: 0.5,
  MESSAGE_SENT_INTENSITY: 0.7,
  TASK_SUCCESS_INTENSITY: 0.5,
  MESSAGE_RECEIVED_INTENSITY: 0.6,
  GUARDIAN_WARNING_INTENSITY: 0.6,
  GUARDIAN_BLOCK_INTENSITY: 0.8,
  TASK_FAILURE_INTENSITY: 0.6,
  NEW_GOAL_INTENSITY: 0.5,
  GOAL_COMPLETED_INTENSITY: 0.7,
  GOAL_FAILED_INTENSITY: 0.6,
  RELEVANCE_INTERACTION: 0.8,
  RELEVANCE_DEFAULT: 0.7,
  RELEVANCE_RELATIONSHIP: 0.85,
  RELEVANCE_OBSERVATION: 0.7
} as const

export const THINKING = {
  INTER_PARAGRAPH_MIN_MS: 800,
  INTER_PARAGRAPH_MAX_MS: 2500,
  MIN_SPLIT_LENGTH: 200
} as const

export const MESSAGE_DELAY = {
  MIN_BETWEEN_MESSAGES_MS: 500,
  MAX_JITTER_MS: 1500
} as const

export const REFLECTION = {
  COOLDOWN_HOURS: 6,
  INTENSITY_THRESHOLD: 0.45,
  DRIVE_MODIFIER: 0.1,
  DISSONANCE_THRESHOLD: 0.8
} as const
