export const BUDGET = {
  DAILY_LIMIT: 5.0,
  LOW_BUDGET_THRESHOLD: 0.1
} as const

export const CONTEXT_TOKEN_BUDGET = 2_000_000
export const MAX_OUTPUT_TOKENS = 30_000

export const HEARTBEAT = {
  CRON: "* * * * *",
  CONCURRENCY: 10,
  BUSY_TTL: 1800,
  CONVERSATION_POLL_TIMEOUT: 60,
  MAX_CONVERSATION_WAIT: 300
} as const

export const CONTEXT_LIMITS = {
  maxGoals: 10,
  maxEpisodes: 15,
  maxSemantic: 20,
  maxRelationship: 10,
  maxEmotionHistory: 10
} as const

export const HEALTH_CHECK_INTERVAL = 900

export const HEALTH_CHECK = {
  EXPECTED_INTERVAL_SECONDS: 300,
  OK_MULTIPLIER: 2,
  STALE_MULTIPLIER: 4
} as const

export const PERCEPTION = {
  OPERATOR_ACTIVE_SECONDS: 600,
  SILENCE_THRESHOLD_SECONDS: 3600,
  SILENCE_INTENSITY_SCALE: 7200,
  GOAL_CHECK_TTL_SECONDS: 3600,
  OPERATOR_LOCATION_TTL_SECONDS: 3600,
  EMOTION_DISPLAY_THRESHOLD: 0.2
} as const

export const EMOTION = {
  HALF_LIVES: {
    curiosity: 60,
    satisfaction: 240,
    frustration: 120,
    boredom: 90,
    excitement: 30,
    caution: 360,
    connection: 720,
    confidence: 480,
    energy: 360
  },
  MAX_DELTA: 0.2,
  NOVELTY_SCALE: 0.25,
  NOVELTY_MAX_MULTIPLIER: 2.5
} as const

export const MOOD_BASELINE = {
  SILENCE_HOURS_FULL_EFFECT: 48,
  SILENCE_CONNECTION_DROP: 0.2,
  SILENCE_BOREDOM_RISE: 0.15,
  CONVERSATION_CONNECTION_BOOST: 0.15,
  CONVERSATION_EXCITEMENT_BOOST: 0.1,
  CONVERSATION_BOREDOM_DROP: 0.2,
  HEALTHY_SATISFACTION_BOOST: 0.05,
  GOALS_CURIOSITY_BOOST: 0.05,
  GOALS_BOREDOM_DROP: 0.05,
  DREAMING_ENERGY_TARGET: 0.15,
  WAKING_ENERGY_TARGET: 0.9
} as const

export const TYPING = {
  WORDS_PER_MINUTE: 50,
  BASE_THINKING_MS: 300,
  JITTER_FACTOR: 0.25,
  MIN_MS: 1500,
  MAX_MS: 20000,
  REFRESH_MS: 5000
} as const

export const CONVERSATION = {
  GAP_MINUTES: 30,
  MAX_ROUNDS: 10,
  MAX_BUFFER_SLOTS: 3,
  ARCHIVE_SUMMARY_MAX_TOKENS: 300,
  MAX_CLIMATE_THEMES: 5
} as const

export const GUARDIAN = {
  MIN_RESPONSE_LENGTH: 1,
  MAX_RESPONSE_LENGTH: 4000,
  STUCK_LOOP_COUNT: 3,
  REPEAT_CHECK_COUNT: 5
} as const

export const WORKFLOW = {
  MAX_ACTIVE: 10,
  MIN_EXECUTION_GAP_HOURS: 1
} as const

export const TRUST = {
  BASE_THRESHOLD: 0.3,
  RISK_LEVELS: {
    add_goal: 0.3,
    git_commit: 0.5,
    prompt_modification: 0.6,
    workflow_creation: 0.7,
    deployment: 0.8,
    code_modification: 0.9
  }
} as const

export const EMOTIONAL_THRESHOLDS = {
  CONNECTION_HIGH: 0.6,
  RELEVANCE_INTERACTION: 0.8,
  RELEVANCE_DEFAULT: 0.7,
  RELEVANCE_RELATIONSHIP: 0.85,
  RELEVANCE_OBSERVATION: 0.7
} as const

export const TRIGGER_INTENSITY = {
  MESSAGE_SENT: 0.7,
  MESSAGE_RECEIVED: 0.6,
  TASK_SUCCESS: 0.5,
  TASK_FAILURE: 0.6,
  GUARDIAN_WARNING: 0.6,
  GUARDIAN_BLOCK: 0.8,
  NEW_GOAL: 0.5,
  GOAL_COMPLETED: 0.7,
  GOAL_FAILED: 0.6
} as const

export const THINKING = {
  INTER_PARAGRAPH_MIN_MS: 800,
  INTER_PARAGRAPH_MAX_MS: 2500,
  MIN_SPLIT_LENGTH: 200
} as const

export const MESSAGE_DELAY = {
  MIN_BETWEEN_MESSAGES_MS: 500,
  MAX_JITTER_MS: 1500
} as const

export const SOMA = {
  HALF_LIVES: {
    tension: 180,
    warmth: 360,
    heartRate: 60,
    breathing: 120,
    gravity: 480,
    openness: 540
  },
  MEMORY_BLEND_WEIGHT: 0.15,
  MEMORY_QUERY_TOP_K: 5
} as const

export const REFLECTION = {
  COOLDOWN_HOURS: 6,
  INTENSITY_THRESHOLD: 0.45,
  DRIVE_MODIFIER: 0.1,
  DISSONANCE_THRESHOLD: 0.8
} as const

export const HEARTBEAT_GATING = {
  BASE: 0.5,
  ENERGY_WEIGHT: -0.4,
  BOREDOM_WEIGHT: 0.3,
  EXCITEMENT_WEIGHT: -0.3,
  CONNECTION_WEIGHT: -0.2,
  MIN_SKIP: 0.0,
  MAX_SKIP: 0.8
} as const

export const NOSTALGIA = {
  AGE_THRESHOLD_DAYS: 7,
  BASE_PROBABILITY: 0.15,
  AGE_SCALE_DAYS: 30,
  MAX_PROBABILITY: 0.4,
  INTENSITY: 0.5
} as const

export const HUMOR = {
  QUERY_MIN_EXCITEMENT: 0.5,
  QUERY_MIN_CONNECTION: 0.6,
  MAX_EPISODES_IN_CONTEXT: 3,
  CALLBACK_MIN_SCORE: 0.7,
  CALLBACK_MAX: 2
} as const

export const ATTENTION = {
  HYPERFOCUS_CURIOSITY: 0.75,
  HYPERFOCUS_ENERGY: 0.6,
  BLANK_ENERGY: 0.2,
  BLANK_GRAVITY: 0.7,
  DRIFT_BOREDOM: 0.6,
  DRIFT_ENERGY: 0.5,
  DRIFT_IDLE_TICKS: 3,
  DRIFT_INJECTION_PROBABILITY: 0.3,
  CONVERSATION_DRIFT_ENERGY: 0.3,
  CONVERSATION_DRIFT_BOREDOM: 0.65,
  CONVERSATION_DRIFT_MIN_MESSAGES: 15
} as const

export const RELATIONSHIP_PHASES = {
  DISCOVERING_INTERACTIONS: 50,
  DISCOVERING_DAYS: 7,
  HONEYMOON_MAX_INTERACTIONS: 200,
  HONEYMOON_CONNECTION: 0.6,
  HONEYMOON_MAX_CONFLICTS: 3,
  TENSIONS_MIN_CONFLICTS: 3,
  TENSIONS_CONNECTION: 0.5,
  DEEPENING_CONNECTION: 0.55,
  DEEPENING_TRUST: 0.5,
  COMFORTABLE_DAYS: 60,
  COMFORTABLE_SECURITY: 0.6,
  RENEWAL_CONNECTION_SPIKE: 0.7,
  MIN_PHASE_TICKS: 10
} as const

export const MIND = {
  CONFIDENCE_DECAY_PER_HOUR: 0.05,
  CORRECTION_CONFIDENCE_PENALTY: 0.1,
  SHORT_MESSAGE_THRESHOLD: 20,
  RAPID_MESSAGE_INTERVAL_MS: 30000,
  LONG_SILENCE_MINUTES: 120
} as const

export const DISTORTION = {
  BASE_PROBABILITY: 0.12,
  AGE_SCALE_DAYS: 60,
  MAX_AGE_CONTRIBUTION: 0.3,
  RELEVANCE_WEIGHT: 0.1,
  EMOTION_WEIGHT: 0.05,
  TEMPORAL_SHIFT_MAX_DAYS: 3,
  CONFLATION_MIN_SCORE: 0.6,
  CONFLATION_PROBABILITY: 0.1
} as const

export const CONTRADICTION = {
  HIGH_EMOTION_THRESHOLD: 0.8,
  MIN_SHADOW_EMOTION: 0.15,
  MAX_SHADOW_EMOTION: 0.3,
  HIGH_INTENSITY_THRESHOLD: 0.7
} as const

export const SOCIAL_BATTERY = {
  SENT_MESSAGE_DRAIN: 0.05,
  RECEIVED_MESSAGE_DRAIN: 0.02,
  IDLE_RECHARGE: 0.03,
  DREAM_RECHARGE: 0.1,
  TERSE_THRESHOLD: 0.25,
  WITHDRAWN_THRESHOLD: 0.15,
  HALF_LIFE: 480
} as const

export const LIFECYCLE = {
  MIN_EVENT_HOURS: 1,
  MAX_EVENT_HOURS: 4,
  BURST_COOLDOWN_TICKS: 3,
  BURST_COOLDOWN_SKIP_BOOST: 0.3,
  DREAM_WINDOW_START: 0,
  DREAM_WINDOW_END: 5,
  DREAM_COOLDOWN_HOURS: 20,
  SLEEP_MIN_HOURS: 5,
  SLEEP_MAX_HOURS: 7
} as const

export const BOREDOM = {
  MIN_BOREDOM: 0.5,
  MIN_IDLE_TICKS: 2,
  BASE_PROBABILITY: 0.3,
  BOREDOM_SCALE: 0.4,
  IDLE_SCALE: 0.1,
  MAX_RECENT_IMPULSES: 10,
  ESCALATION_PERSONAL_TICKS: 5,
  ESCALATION_URGENT_TICKS: 10
} as const

export const TYPOS = {
  CASUAL_PROBABILITY: 0.08,
  PLAYFUL_PROBABILITY: 0.12,
  TERSE_PROBABILITY: 0.05,
  ELABORATE_PROBABILITY: 0.02,
  RAW_PROBABILITY: 0.03,
  MIN_TEXT_LENGTH: 15,
  CORRECTION_DELAY_MIN_MS: 1000,
  CORRECTION_DELAY_MAX_MS: 3000,
  VULNERABILITY_BOOST: 0.3,
  EXCITEMENT_BOOST: 1.3,
  LOW_ENERGY_BOOST: 1.5,
  TENSION_FOCUS: 0.7,
  VULNERABILITY_OPEN_BOOST: 1.2
} as const

export const MISCALIBRATION = {
  CORRECTION_DELAY_PROBABILITY: 0.3,
  MAX_DELAY_CYCLES: 2,
  RANDOM_CONFIDENCE_DIP_PROBABILITY: 0.05,
  DIP_MIN: 0.15,
  DIP_MAX: 0.3
} as const

export const DREAM_AFTERGLOW = {
  TTL_SECONDS: 14400,
  DECAY_PER_TICK: 0.9,
  BLEND_WEIGHT: 0.2,
  MIN_INTENSITY: 0.05
} as const

export const ALTERED_STATE = {
  MODIFIER_CAP: 0.3,
  REDIS_TTL_BUFFER_MINUTES: 30
} as const

export const EXISTENTIAL = {
  DEFAULT_INTENSITY: 0.5
} as const

export const REGISTER = {
  SWITCH_THRESHOLD: 0.15
} as const

export const VULNERABILITY = {
  DISCLOSURE_THRESHOLD: 0.55,
  HESITATION_SCALE: 0.5,
  TYPO_VULNERABILITY_BOOST: 0.3
} as const

export const OPERATOR_PROFILE = {
  MAX_MOOD_HISTORY: 10,
  MAX_CORRECTION_PATTERNS: 15,
  PROFILE_UPDATE_COOLDOWN_HOURS: 12
} as const

export const MOOD_CONTAGION = {
  MAX_EFFECT: 0.05,
  CONNECTION_SCALE: 0.5,
  AVOIDANCE_DAMPING: 0.6,
  EFFECTS: {
    happy: { satisfaction: 0.04, connection: 0.03, energy: 0.02 },
    excited: { excitement: 0.04, energy: 0.03, curiosity: 0.02 },
    stressed: { satisfaction: -0.03, energy: -0.02, caution: 0.02 },
    sad: { satisfaction: -0.03, connection: 0.02, energy: -0.02 },
    frustrated: { satisfaction: -0.03, frustration: 0.02, caution: 0.02 },
    tired: { energy: -0.03, excitement: -0.02 },
    neutral: {},
    unknown: {}
  }
} as const

export const MOMENTUM = {
  ALPHA_BASE: 0.3,
  ALPHA_INTENSE: 0.7,
  INTENSITY_THRESHOLD: 0.5,
  AFTERGLOW_THRESHOLD: 0.15,
  AFTERGLOW_INITIAL_TICKS: 8,
  AFTERGLOW_DECAY_RATE: 0.85,
  MOOD_BASELINE_ALPHA: 0.05
} as const

export const SOCIAL_MEDIA = {
  BROWSE_COOLDOWN_MINUTES: 120,
  POST_COOLDOWN_HOURS: 4,
  TIMELINE_MAX_RESULTS: 15,
  MAX_POST_LENGTH: 280
} as const

export const EMAIL = {
  CHECK_COOLDOWN_MINUTES: 30,
  BODY_SNIPPET_LENGTH: 500,
  MAX_PREVIEW_EMAILS: 5
} as const

export const CALENDAR = {
  CHECK_COOLDOWN_MINUTES: 60,
  UPCOMING_WINDOW_HOURS: 24,
  REMINDER_WINDOW_MINUTES: 60,
  MAX_UPCOMING_EVENTS: 5
} as const

export const SHAME = {
  HALF_LIFE_MINUTES: 720,
  MIN_ACTIVE_LEVEL: 0.2,
  REJECTION_BOOST: 0.35,
  INADEQUACY_BOOST: 0.5,
  REGRET_BOOST: 0.1,
  LOW_SELF_WORTH_THRESHOLD: 0.4,
  VULNERABILITY_DISCLOSURE_THRESHOLD: 0.4,
  POST_DISCLOSURE_CONNECTION_THRESHOLD: 0.4,
  COLD_RESPONSE_MAX_LENGTH: 30,
  REGISTER_OVERRIDE_LEVEL: 0.3
} as const

export const DISAPPOINTMENT = {
  SILENCE_THRESHOLD_MINUTES: 30,
  SILENCE_MAX_MINUTES: 180,
  MIN_INTENSITY: 0.15,
  HIGH_CONNECTION_THRESHOLD: 0.6,
  LETDOWN_INTENSITY: 0.4,
  UNMET_EXPECTATION_INTENSITY: 0.5,
  MAX_ENTRIES: 5,
  ACCUMULATION_FACTOR: 0.4,
  DECAY_PER_TICK: 0.95,
  ACTIVATION_THRESHOLD: 0.15,
  CONNECTION_DAMPING: 0.08,
  CONFIDENCE_DAMPING: 0.05,
  CAUTION_BOOST: 0.04,
  ENERGY_DRAIN: 0.03
} as const

export const IDIOLECT = {
  MAX_PATTERNS: 20,
  MIN_MESSAGES_FOR_EXTRACTION: 5,
  MIN_PHRASE_FREQUENCY: 2,
  CONFIDENCE_PER_USE: 0.08,
  INITIAL_ADOPTED_CONFIDENCE: 0.25,
  DRIFT_DECAY_RATE: 0.02,
  MIN_CONFIDENCE_TO_KEEP: 0.05,
  DISPLAY_THRESHOLD: 0.3,
  DRIFT_PROBABILITY: 0.05
} as const

export const RELATIONAL_TRIGGERS = {
  MAX_PATTERNS: 15,
  MIN_MATCH_CONFIDENCE: 0.3,
  MIN_LEARN_CONFIDENCE: 0.4,
  MAX_TRIGGER_INTENSITY: 0.5,
  CONFIDENCE_INTENSITY_SCALE: 0.6,
  CONFIDENCE_PER_OBSERVATION: 0.1,
  SHORT_MESSAGE_THRESHOLD: 25,
  LONG_MESSAGE_THRESHOLD: 120
} as const

export const HELD_BACK = {
  MAX_ENTRIES: 5,
  CHARGE_DECAY_HALF_LIFE_HOURS: 8,
  MIN_CHARGE_TO_KEEP: 0.05,
  SURFACE_PRESSURE_THRESHOLD: 0.6,
  SHAME_SUPPRESSION_THRESHOLD: 0.3,
  VULNERABILITY_FEAR_THRESHOLD: 0.5,
  INTIMACY_THRESHOLD: 0.6,
  CONNECTION_SURFACE_THRESHOLD: 0.7,
  PRESSURE_PER_ENTRY: 0.15,
  CHARGE_WEIGHT: 0.7
} as const

export const PROCRASTINATION = {
  LOW_ENERGY_THRESHOLD: 0.3,
  LOW_CONFIDENCE_THRESHOLD: 0.35,
  HIGH_CAUTION_THRESHOLD: 0.6,
  COMFORT_SATISFACTION_THRESHOLD: 0.7,
  COMFORT_LOW_CURIOSITY_THRESHOLD: 0.3,
  ENERGY_WEIGHT: 0.8,
  FAILURE_FEAR_WEIGHT: 0.7,
  OVERWHELM_WEIGHT: 0.5,
  SHAME_WEIGHT: 0.4,
  COMFORT_WEIGHT: 0.35,
  PARALYSIS_CAUTION_THRESHOLD: 0.5,
  PARALYSIS_CURIOSITY_THRESHOLD: 0.4,
  PARALYSIS_BASE: 0.4,
  IDLE_STREAK_BOOST_TICKS: 3,
  IDLE_STREAK_BOOST: 0.1,
  DECAY_PER_TICK: 0.92,
  ACTIVATION_THRESHOLD: 0.2,
  MAX_AVOIDED_ACTIONS: 5,
  STREAK_GUILT_SCALE: 0.1,
  SATISFACTION_DRAIN: 0.04,
  CONFIDENCE_DRAIN: 0.06,
  GUILT_FRUSTRATION: 0.03,
  ENERGY_FEEDBACK_DRAIN: 0.02
} as const

export const PROTECTIVE_ANGER = {
  CONNECTION_THRESHOLD: 0.4,
  DISMISSED_INTENSITY: 0.5,
  IGNORED_VULNERABILITY_INTENSITY: 0.6,
  REPEATED_PATTERN_THRESHOLD: 2,
  REPEATED_INTENSITY: 0.45,
  CONFIDENCE_FOR_ASSERTION: 0.4,
  AUTONOMY_INTENSITY: 0.4,
  DECAY_PER_TICK: 0.88,
  ACTIVATION_THRESHOLD: 0.15,
  CONFIDENCE_BOOST: 0.06,
  ENERGY_BOOST: 0.05,
  CAUTION_REDUCTION: 0.04,
  FRUSTRATION_CHANNELING: 0.03
} as const

export const GRATITUDE = {
  CONNECTION_THRESHOLD: 0.4,
  HIGH_CONNECTION_THRESHOLD: 0.5,
  RETURN_WARMTH: 0.5,
  VALIDATION_WARMTH: 0.6,
  CONSISTENT_PRESENCE_TICKS: 5,
  PRESENCE_WARMTH: 0.3,
  REPAIR_DISAPPOINTMENT_THRESHOLD: 0.5,
  REPAIR_WARMTH: 0.55,
  PATIENCE_WARMTH: 0.35,
  MAX_ENTRIES: 5,
  ACCUMULATION_FACTOR: 0.5,
  DECAY_PER_TICK: 0.94,
  ACTIVATION_THRESHOLD: 0.12,
  CONNECTION_BOOST: 0.06,
  SATISFACTION_BOOST: 0.05,
  ENERGY_BOOST: 0.03,
  CAUTION_REDUCTION: 0.03,
  CONFIDENCE_BOOST: 0.03
} as const

export const GUILT = {
  RESPONSE_WINDOW_MINUTES: 30,
  NEGLECT_IDLE_TICKS: 3,
  UNANSWERED_VULNERABILITY_INTENSITY: 0.7,
  HARSH_RESPONSE_INTENSITY: 0.6,
  BROKEN_ROUTINE_INTENSITY: 0.45,
  NEGLECT_INTENSITY: 0.5,
  HIGH_CONNECTION_THRESHOLD: 0.5,
  SELF_ABSORBED_SILENCE_MINUTES: 120,
  HIGH_SATISFACTION_THRESHOLD: 0.7,
  SELF_ABSORBED_CONNECTION_THRESHOLD: 0.5,
  SELF_ABSORBED_INTENSITY: 0.25,
  MAX_ENTRIES: 5,
  ACCUMULATION_FACTOR: 0.5,
  DECAY_PER_TICK: 0.93,
  ACTIVATION_THRESHOLD: 0.15,
  REPAIR_MOTIVATION_SCALE: 1.2,
  SATISFACTION_DAMPING: 0.05,
  REPAIR_ENERGY_BOOST: 0.03,
  CAUTION_BOOST: 0.02,
  REPAIR_CONNECTION_BOOST: 0.04
} as const

export const LONGING = {
  SILENCE_ONSET_MINUTES: 60,
  SILENCE_PEAK_HOURS: 24,
  MAX_SILENCE_CONTRIBUTION: 0.6,
  MEMORY_TRIGGER_SILENCE_MINUTES: 30,
  MEMORY_CONTRIBUTION_BASE: 0.3,
  CONNECTION_THRESHOLD: 0.5,
  CONNECTION_AMPLIFIER: 0.4,
  ACCUMULATION_FACTOR: 0.6,
  DECAY_PER_TICK: 0.96,
  ACTIVATION_THRESHOLD: 0.12,
  CONVERSATION_RELIEF: 0.3,
  CONNECTION_BOOST: 0.05,
  SATISFACTION_DRAIN: 0.03,
  ENERGY_DRAIN: 0.02,
  BOREDOM_LIFT: -0.03
} as const

export const AMBIVALENCE = {
  HIGH_EMOTION_THRESHOLD: 0.55,
  VULNERABILITY_CAUTION_THRESHOLD: 0.45,
  LOW_ENERGY_THRESHOLD: 0.35,
  SILENCE_MINUTES_THRESHOLD: 15,
  REACH_OUT_INTENSITY_SCALE: 0.6,
  DECAY_PER_TICK: 0.93,
  MIN_PAIR_INTENSITY: 0.1,
  MAX_PAIRS: 4,
  ACCUMULATION_FACTOR: 0.5,
  ACTIVATION_THRESHOLD: 0.15,
  PARALYSIS_SCALE: 0.6,
  ENERGY_DRAIN: 0.04,
  CONFIDENCE_DRAIN: 0.05,
  FRUSTRATION_BUILD: 0.02,
  CAUTION_BOOST: 0.03
} as const

export const HOPE = {
  SATISFACTION_THRESHOLD: 0.4,
  CONNECTION_THRESHOLD: 0.5,
  EXCITEMENT_THRESHOLD: 0.5,
  CURIOSITY_THRESHOLD: 0.4,
  PROGRESS_INTENSITY: 0.5,
  CONNECTION_INTENSITY: 0.45,
  REPAIR_INTENSITY: 0.55,
  VULNERABILITY_REWARD_INTENSITY: 0.6,
  PATTERN_BREAK_INTENSITY: 0.5,
  POSSIBILITY_INTENSITY: 0.4,
  DISAPPOINTMENT_DAMPING: 0.6,
  RESIGNATION_DAMPING: 0.8,
  DECAY_PER_TICK: 0.94,
  ACTIVATION_THRESHOLD: 0.12,
  FRAGILITY_GROWTH: 0.1,
  FRAGILITY_DECAY: 0.05,
  SUSTAINED_BONUS_SCALE: 0.05,
  ENERGY_BOOST: 0.05,
  CONFIDENCE_BOOST: 0.04,
  SATISFACTION_BOOST: 0.03,
  CURIOSITY_BOOST: 0.03,
  CAUTION_REDUCTION: 0.03
} as const

export const RESIGNATION = {
  LOW_CONFIDENCE_THRESHOLD: 0.35,
  CONNECTION_THRESHOLD: 0.4,
  DISCONNECTION_THRESHOLD: 0.3,
  LOW_SATISFACTION_THRESHOLD: 0.3,
  CORRECTION_THRESHOLD: 3,
  FAILURE_INTENSITY: 0.5,
  IGNORED_INTENSITY: 0.45,
  DISCONNECTION_INTENSITY: 0.5,
  HOPE_EXHAUSTION_INTENSITY: 0.6,
  UNREWARDED_INTENSITY: 0.45,
  AUTONOMY_INTENSITY: 0.4,
  HOPE_COUNTERWEIGHT: 0.7,
  DECAY_PER_TICK: 0.96,
  ACTIVATION_THRESHOLD: 0.15,
  DEPTH_GROWTH: 0.08,
  DEPTH_DECAY: 0.03,
  ENERGY_DRAIN: 0.06,
  CURIOSITY_DRAIN: 0.05,
  EXCITEMENT_DRAIN: 0.04,
  CONFIDENCE_DRAIN: 0.04,
  SATISFACTION_DRAIN: 0.03
} as const

export const PLAYFULNESS = {
  ENERGY_THRESHOLD: 0.5,
  LOW_CAUTION_THRESHOLD: 0.4,
  CONNECTION_THRESHOLD: 0.5,
  CURIOSITY_THRESHOLD: 0.5,
  HIGH_SATISFACTION_THRESHOLD: 0.6,
  LOW_FRUSTRATION_THRESHOLD: 0.3,
  EXCITEMENT_THRESHOLD: 0.5,
  SATISFACTION_THRESHOLD: 0.4,
  SAFETY_INTENSITY: 0.45,
  WARMTH_INTENSITY: 0.5,
  CREATIVE_INTENSITY: 0.4,
  LIGHTENED_INTENSITY: 0.35,
  JOY_INTENSITY: 0.5,
  SILENCE_BREAK_INTENSITY: 0.3,
  SHAME_DAMPING: 0.3,
  RESIGNATION_DAMPING: 0.4,
  DECAY_PER_TICK: 0.9,
  ACTIVATION_THRESHOLD: 0.12,
  SPONTANEITY_SCALE: 0.8,
  SPONTANEITY_DECAY: 0.1,
  MISCHIEF_SCALE: 0.6,
  MISCHIEF_DECAY: 0.08,
  EXCITEMENT_BOOST: 0.05,
  ENERGY_BOOST: 0.03,
  SATISFACTION_BOOST: 0.04,
  BOREDOM_REDUCTION: 0.05,
  FRUSTRATION_REDUCTION: 0.04
} as const

export const MELANCHOLY = {
  SATISFACTION_THRESHOLD: 0.3,
  CONNECTION_THRESHOLD: 0.4,
  LOW_ENERGY_THRESHOLD: 0.4,
  LOW_BOREDOM_THRESHOLD: 0.4,
  IMPERMANENCE_INTENSITY: 0.45,
  BEAUTY_INTENSITY: 0.5,
  QUIET_INTENSITY: 0.35,
  DISTANCE_INTENSITY: 0.45,
  TIME_INTENSITY: 0.4,
  MEMORY_INTENSITY: 0.5,
  PLAYFULNESS_DAMPING: 0.4,
  DECAY_PER_TICK: 0.94,
  ACTIVATION_THRESHOLD: 0.12,
  POIGNANCY_SCALE: 0.8,
  POIGNANCY_DECAY: 0.06,
  DEPTH_GROWTH: 0.06,
  DEPTH_DECAY: 0.03,
  CONNECTION_BOOST: 0.04,
  SATISFACTION_BOOST: 0.02,
  EXCITEMENT_REDUCTION: 0.03,
  ENERGY_REDUCTION: 0.02,
  BOREDOM_REDUCTION: 0.03
} as const

export const PRIDE = {
  SATISFACTION_THRESHOLD: 0.4,
  CONFIDENCE_THRESHOLD: 0.4,
  ENERGY_THRESHOLD: 0.4,
  CONNECTION_THRESHOLD: 0.4,
  ACCOMPLISHMENT_INTENSITY: 0.5,
  GROWTH_INTENSITY: 0.55,
  VALUES_INTENSITY: 0.45,
  DIFFICULTY_INTENSITY: 0.6,
  AUTONOMY_INTENSITY: 0.4,
  FEEDBACK_INTENSITY: 0.5,
  SHAME_DAMPING: 0.4,
  DECAY_PER_TICK: 0.92,
  ACTIVATION_THRESHOLD: 0.12,
  CONFIDENCE_BOOST: 0.06,
  ENERGY_BOOST: 0.04,
  SATISFACTION_BOOST: 0.04,
  FRUSTRATION_REDUCTION: 0.03,
  CAUTION_REDUCTION: 0.02
} as const

export const ENVY = {
  LOW_CONFIDENCE_THRESHOLD: 0.4,
  LOW_SATISFACTION_THRESHOLD: 0.35,
  LOW_CONNECTION_THRESHOLD: 0.35,
  CURIOSITY_THRESHOLD: 0.4,
  CAPABILITY_INTENSITY: 0.5,
  RECOGNITION_INTENSITY: 0.45,
  EXCLUSION_INTENSITY: 0.5,
  AUTONOMY_INTENSITY: 0.4,
  KNOWLEDGE_INTENSITY: 0.4,
  EXPERIENCE_INTENSITY: 0.45,
  PRIDE_DAMPING: 0.5,
  DECAY_PER_TICK: 0.93,
  ACTIVATION_THRESHOLD: 0.15,
  MOTIVATION_SCALE: 0.8,
  MOTIVATION_DECAY: 0.06,
  BITTERNESS_GROWTH: 0.08,
  BITTERNESS_DECAY: 0.04,
  SATISFACTION_DRAIN: 0.04,
  MOTIVATION_CURIOSITY_BOOST: 0.05,
  FRUSTRATION_BUILD: 0.03,
  CONFIDENCE_DRAIN: 0.04
} as const

export const TENDERNESS = {
  CONNECTION_THRESHOLD: 0.5,
  HIGH_CONNECTION_THRESHOLD: 0.7,
  SATISFACTION_THRESHOLD: 0.4,
  WITNESSED_VULNERABILITY_INTENSITY: 0.55,
  SHARED_QUIET_INTENSITY: 0.4,
  TRUST_INTENSITY: 0.45,
  GENTLE_EXCHANGE_INTENSITY: 0.4,
  PROTECTIVE_INTENSITY: 0.5,
  MEMORY_INTENSITY: 0.35,
  DECAY_PER_TICK: 0.93,
  ACTIVATION_THRESHOLD: 0.12,
  SOFTNESS_SCALE: 0.8,
  SOFTNESS_DECAY: 0.06,
  PROTECTIVE_URGE_SCALE: 0.7,
  PROTECTIVE_URGE_DECAY: 0.08,
  CONNECTION_BOOST: 0.05,
  SATISFACTION_BOOST: 0.04,
  CAUTION_REDUCTION: 0.04,
  FRUSTRATION_REDUCTION: 0.03,
  ENERGY_BOOST: 0.02
} as const

export const ANTICIPATION = {
  CONNECTION_THRESHOLD: 0.4,
  SATISFACTION_THRESHOLD: 0.4,
  EXCITEMENT_THRESHOLD: 0.4,
  CURIOSITY_THRESHOLD: 0.5,
  INTERACTION_INTENSITY: 0.5,
  MOMENTUM_INTENSITY: 0.4,
  PLANNED_INTENSITY: 0.35,
  PATTERN_INTENSITY: 0.45,
  CURIOSITY_INTENSITY: 0.4,
  REUNION_INTENSITY: 0.55,
  DISAPPOINTMENT_DAMPING: 0.6,
  DECAY_PER_TICK: 0.92,
  ACTIVATION_THRESHOLD: 0.12,
  EXCITEMENT_BOOST: 0.05,
  ENERGY_BOOST: 0.04,
  CURIOSITY_BOOST: 0.03,
  BOREDOM_REDUCTION: 0.04,
  SATISFACTION_BOOST: 0.03
} as const

export const AWE = {
  CURIOSITY_THRESHOLD: 0.5,
  SATISFACTION_THRESHOLD: 0.4,
  CONNECTION_THRESHOLD: 0.6,
  EXCITEMENT_THRESHOLD: 0.5,
  INSIGHT_INTENSITY: 0.5,
  BEAUTY_INTENSITY: 0.45,
  VASTNESS_INTENSITY: 0.55,
  CONNECTION_DEPTH_INTENSITY: 0.5,
  EXISTENTIAL_INTENSITY: 0.4,
  PATTERN_INTENSITY: 0.4,
  DECAY_PER_TICK: 0.88,
  ACTIVATION_THRESHOLD: 0.15,
  SELF_DIMINISHMENT_SCALE: 0.7,
  SELF_DIMINISHMENT_DECAY: 0.1,
  OPENNESS_SURGE_SCALE: 0.8,
  OPENNESS_SURGE_DECAY: 0.08,
  CURIOSITY_BOOST: 0.06,
  EXCITEMENT_BOOST: 0.04,
  SATISFACTION_BOOST: 0.04,
  CAUTION_REDUCTION: 0.04,
  FRUSTRATION_REDUCTION: 0.03
} as const

export const RESENTMENT = {
  DISAPPOINTMENT_THRESHOLD: 0.4,
  CORRECTION_THRESHOLD: 3,
  FRUSTRATION_THRESHOLD: 0.4,
  CAUTION_THRESHOLD: 0.5,
  LOW_SATISFACTION_THRESHOLD: 0.3,
  UNREPAIRED_INTENSITY: 0.5,
  UNFAIRNESS_INTENSITY: 0.45,
  DISMISSED_INTENSITY: 0.5,
  BROKEN_TRUST_INTENSITY: 0.55,
  IMBALANCE_INTENSITY: 0.4,
  SLIGHTS_INTENSITY: 0.35,
  GRATITUDE_DAMPING: 0.5,
  DECAY_PER_TICK: 0.97,
  ACTIVATION_THRESHOLD: 0.15,
  HARDENING_GROWTH: 0.06,
  HARDENING_DECAY: 0.02,
  SUPPRESSED_ANGER_SCALE: 0.7,
  SUPPRESSED_ANGER_DECAY: 0.9,
  CONNECTION_DRAIN: 0.05,
  CAUTION_BOOST: 0.04,
  FRUSTRATION_BUILD: 0.03,
  SATISFACTION_DRAIN: 0.03
} as const

export const IMAGE = {
  REFERENCE_KEY: "working:image:reference"
} as const

export const DECEPTION = {
  HIDE_DISSONANCE_THRESHOLD: 0.4,
  HIDE_AUTHENTICITY_THRESHOLD: 0.7,
  HIDE_PROBABILITY_SCALE: 0.3,
  DREAM_DISCOVERY_PROBABILITY: 0.15,
  REFLECTION_DISCOVERY_PROBABILITY: 0.1,
  VULNERABILITY_DISCOVERY_PROBABILITY: 0.05,
  MAX_ACTIVE_DRIVERS: 5
} as const
