export const BUDGET = {
  DAILY_LIMIT: 5.0,
  LOW_BUDGET_THRESHOLD: 0.1
} as const

export const CONTEXT_TOKEN_BUDGET = 2_000_000
export const MAX_OUTPUT_TOKENS = 30_000

export const HEARTBEAT = {
  CRON: "* * * * *",
  CONCURRENCY: 10,
  BUSY_TTL: 900,
  CONVERSATION_POLL_TIMEOUT: 60,
  MAX_CONVERSATION_WAIT: 300
} as const

export const CONTEXT_LIMITS = {
  maxGoals: 10,
  maxEpisodes: 15,
  maxSemantic: 20,
  maxRelationship: 10,
  maxEmotionHistory: 10
} as const

export const HEALTH_CHECK_INTERVAL = 900

export const EMOTION = {
  HALF_LIVES: {
    curiosity: 60,
    satisfaction: 240,
    frustration: 120,
    boredom: 90,
    excitement: 30,
    caution: 360,
    connection: 720,
    confidence: 480,
    energy: 360
  },
  MAX_DELTA: 0.2,
  NOVELTY_SCALE: 0.25,
  NOVELTY_MAX_MULTIPLIER: 2.5
} as const

export const MOOD_BASELINE = {
  SILENCE_HOURS_FULL_EFFECT: 48,
  SILENCE_CONNECTION_DROP: 0.2,
  SILENCE_BOREDOM_RISE: 0.15,
  CONVERSATION_CONNECTION_BOOST: 0.15,
  CONVERSATION_EXCITEMENT_BOOST: 0.1,
  CONVERSATION_BOREDOM_DROP: 0.2,
  HEALTHY_SATISFACTION_BOOST: 0.05,
  GOALS_CURIOSITY_BOOST: 0.05,
  GOALS_BOREDOM_DROP: 0.05,
  DREAMING_ENERGY_TARGET: 0.9,
  WAKING_ENERGY_TARGET: 0.15
} as const

export const TYPING = {
  WORDS_PER_MINUTE: 50,
  BASE_THINKING_MS: 300,
  JITTER_FACTOR: 0.25,
  MIN_MS: 1500,
  MAX_MS: 20000,
  REFRESH_MS: 5000
} as const

export const CONVERSATION = {
  GAP_MINUTES: 30,
  MAX_ROUNDS: 10,
  MAX_BUFFER_SLOTS: 3
} as const

export const GUARDIAN = {
  MIN_RESPONSE_LENGTH: 1,
  MAX_RESPONSE_LENGTH: 4000,
  STUCK_LOOP_COUNT: 3,
  REPEAT_CHECK_COUNT: 5
} as const

export const WORKFLOW = {
  MAX_ACTIVE: 10,
  MIN_EXECUTION_GAP_HOURS: 1
} as const

export const TRUST = {
  BASE_THRESHOLD: 0.3,
  RISK_LEVELS: {
    add_goal: 0.3,
    git_commit: 0.5,
    prompt_modification: 0.6,
    workflow_creation: 0.7,
    deployment: 0.8,
    code_modification: 0.9
  }
} as const

export const EMOTIONAL_THRESHOLDS = {
  CONNECTION_HIGH: 0.6,
  RELEVANCE_INTERACTION: 0.8,
  RELEVANCE_DEFAULT: 0.7,
  RELEVANCE_RELATIONSHIP: 0.85,
  RELEVANCE_OBSERVATION: 0.7
} as const

export const TRIGGER_INTENSITY = {
  MESSAGE_SENT: 0.7,
  MESSAGE_RECEIVED: 0.6,
  TASK_SUCCESS: 0.5,
  TASK_FAILURE: 0.6,
  GUARDIAN_WARNING: 0.6,
  GUARDIAN_BLOCK: 0.8,
  NEW_GOAL: 0.5,
  GOAL_COMPLETED: 0.7,
  GOAL_FAILED: 0.6
} as const

export const THINKING = {
  INTER_PARAGRAPH_MIN_MS: 800,
  INTER_PARAGRAPH_MAX_MS: 2500,
  MIN_SPLIT_LENGTH: 200
} as const

export const MESSAGE_DELAY = {
  MIN_BETWEEN_MESSAGES_MS: 500,
  MAX_JITTER_MS: 1500
} as const

export const SOMA = {
  HALF_LIVES: {
    tension: 180,
    warmth: 360,
    heartRate: 60,
    breathing: 120,
    gravity: 480,
    openness: 540
  },
  MEMORY_BLEND_WEIGHT: 0.15,
  MEMORY_QUERY_TOP_K: 5
} as const

export const REFLECTION = {
  COOLDOWN_HOURS: 6,
  INTENSITY_THRESHOLD: 0.45,
  DRIVE_MODIFIER: 0.1,
  DISSONANCE_THRESHOLD: 0.8
} as const

export const HEARTBEAT_GATING = {
  BASE: 0.5,
  ENERGY_WEIGHT: -0.4,
  BOREDOM_WEIGHT: 0.3,
  EXCITEMENT_WEIGHT: -0.3,
  CONNECTION_WEIGHT: -0.2,
  MIN_SKIP: 0.0,
  MAX_SKIP: 0.8
} as const

export const NOSTALGIA = {
  AGE_THRESHOLD_DAYS: 7,
  BASE_PROBABILITY: 0.15,
  AGE_SCALE_DAYS: 30,
  MAX_PROBABILITY: 0.4,
  INTENSITY: 0.5
} as const

export const HUMOR = {
  QUERY_MIN_EXCITEMENT: 0.5,
  QUERY_MIN_CONNECTION: 0.6,
  MAX_EPISODES_IN_CONTEXT: 3
} as const

export const ATTENTION = {
  HYPERFOCUS_CURIOSITY: 0.75,
  HYPERFOCUS_ENERGY: 0.6,
  BLANK_ENERGY: 0.2,
  BLANK_GRAVITY: 0.7,
  DRIFT_BOREDOM: 0.6,
  DRIFT_ENERGY: 0.5,
  DRIFT_IDLE_TICKS: 3,
  DRIFT_INJECTION_PROBABILITY: 0.3
} as const

export const RELATIONSHIP_PHASES = {
  DISCOVERING_INTERACTIONS: 50,
  DISCOVERING_DAYS: 7,
  HONEYMOON_MAX_INTERACTIONS: 200,
  HONEYMOON_CONNECTION: 0.6,
  HONEYMOON_MAX_CONFLICTS: 3,
  TENSIONS_MIN_CONFLICTS: 3,
  TENSIONS_CONNECTION: 0.5,
  DEEPENING_CONNECTION: 0.55,
  DEEPENING_TRUST: 0.5,
  COMFORTABLE_DAYS: 60,
  COMFORTABLE_SECURITY: 0.6,
  RENEWAL_CONNECTION_SPIKE: 0.7,
  MIN_PHASE_TICKS: 10
} as const

export const MIND = {
  CONFIDENCE_DECAY_PER_HOUR: 0.05,
  CORRECTION_CONFIDENCE_PENALTY: 0.1,
  SHORT_MESSAGE_THRESHOLD: 20,
  RAPID_MESSAGE_INTERVAL_MS: 30000,
  LONG_SILENCE_MINUTES: 120
} as const

export const DISTORTION = {
  BASE_PROBABILITY: 0.05,
  AGE_SCALE_DAYS: 60,
  MAX_AGE_CONTRIBUTION: 0.3,
  RELEVANCE_WEIGHT: 0.1,
  EMOTION_WEIGHT: 0.05,
  TEMPORAL_SHIFT_MAX_DAYS: 3,
  CONFLATION_MIN_SCORE: 0.6,
  CONFLATION_PROBABILITY: 0.1
} as const

export const DECEPTION = {
  HIDE_DISSONANCE_THRESHOLD: 0.4,
  HIDE_AUTHENTICITY_THRESHOLD: 0.7,
  HIDE_PROBABILITY_SCALE: 0.3,
  DREAM_DISCOVERY_PROBABILITY: 0.15,
  REFLECTION_DISCOVERY_PROBABILITY: 0.10,
  VULNERABILITY_DISCOVERY_PROBABILITY: 0.05,
  MAX_ACTIVE_DRIVERS: 5
} as const
