export const FORECASTING = {
  IMPACT_BIAS_MULTIPLIER: 1.8,
  DURATION_BIAS_MULTIPLIER: 2.5,
  FOCALISM_WEIGHT: 0.7,
  IMMUNE_NEGLECT_FACTOR: 0.6,
  BIAS_LEARNING_RATE: 0.03,
  MIN_BIAS_STRENGTH: 0.2,
  FORECAST_COOLDOWN_TICKS: 10,
  FORECAST_PROBABILITY: 0.08,
  RESOLUTION_WINDOW_TICKS: 30,
  MAX_RECENT_ACCURACIES: 20,
  ANTICIPATION_MODULATION_SCALE: 0.05,
  DIFFUSE_SPREAD_SCALE: 0.3,
  DIFFUSE_DELTA_THRESHOLD: 0.02,
  RESOLVE_DELTA_THRESHOLD: 0.05,
  ACCURACY_EMA_ALPHA: 0.1,
  ACCURACY_DURATION_NORMALIZER: 30,
  NEUTRAL_FORECAST_INTENSITY: 0.3,
  NEUTRAL_FORECAST_DURATION: 5,
  BASE_DURATION_OFFSET: 5,
  BASE_DURATION_SCALE: 10,
  FORECAST_TRIGGERS: [
    "operator_went_silent",
    "expectation_violated",
    "positive_anticipation",
    "goal_progress"
  ] as string[]
} as const
