export const FLOW_DETECTION = {
  CURIOSITY_THRESHOLD: 0.6,
  MASTERY_DRIVE_THRESHOLD: 0.5,
  ANXIETY_CEILING: 0.35,
  ATTENTION_THRESHOLD: 0.65,
  CHALLENGE_SKILL_MIN: 0.4,
  CHALLENGE_SKILL_MAX: 0.7,
  MIN_CONSECUTIVE_TICKS: 3,
  DETECTION_PROBABILITY: 0.15,
  FATIGUE_PAUSE_REDUCTION: 0.5,
  TIME_DILATION_FACTOR: -0.4,
  SELF_AWARENESS_REDUCTION: 0.3
} as const
