export const RELATIONAL_MEMORY = {
  RITUAL_MIN_OCCURRENCES: 3,
  RITUAL_MAX_GAP_DAYS: 14,
  MAX_RITUALS: 10,
  MAX_KEY_MOMENTS: 20,
  NARRATIVE_UPDATE_COOLDOWN_HOURS: 24,
  EMOTIONAL_SIGNIFICANCE_THRESHOLD: 0.5
} as const
