export const RELATIONAL_MEMORY = {
  RITUAL_MIN_OCCURRENCES: 3,
  RITUAL_MAX_GAP_DAYS: 14,
  MAX_RITUALS: 15,
  MAX_KEY_MOMENTS: 20,
  NARRATIVE_UPDATE_COOLDOWN_HOURS: 24,
  EMOTIONAL_SIGNIFICANCE_THRESHOLD: 0.5
} as const

export const EPISODIC_LIFECYCLE = {
  EPISODE_PRESSURE_THRESHOLD: 2000,
  SUMMARIZE_TOP_K: 200,
  FORGET_TOP_K: 200
} as const
