export const RELATIONAL_MEMORY = {
  RITUAL_MIN_OCCURRENCES: 3,
  RITUAL_MAX_GAP_DAYS: 14,
  MAX_RITUALS: 15,
  MAX_KEY_MOMENTS: 20,
  NARRATIVE_UPDATE_COOLDOWN_HOURS: 24,
  EMOTIONAL_SIGNIFICANCE_THRESHOLD: 0.5
} as const

export const EPISODIC_LIFECYCLE = {
  EPISODE_PRESSURE_THRESHOLD: 2000,
  SUMMARIZE_TOP_K: 200,
  FORGET_TOP_K: 200
} as const

export const RECONSOLIDATION = {
  BASE_BLEND_FACTOR: 0.1,
  HIGH_RELEVANCE_THRESHOLD: 0.8,
  HIGH_RELEVANCE_BLEND_FACTOR: 0.15,
  YOUNG_MEMORY_BLEND_FACTOR: 0.05,
  YOUNG_MEMORY_HOURS: 6,
  COOLDOWN_MINUTES: 60,
  MAX_BLEND_FACTOR: 0.25,
  DREAM_BLEND_MULTIPLIER: 1.5,
  RECOUNT_MALLEABILITY_FACTOR: 0.01,
  MAX_RECOUNT_BONUS: 0.1
} as const
