export const LIFECYCLE = {
  MIN_EVENT_HOURS: 1,
  MAX_EVENT_HOURS: 4,
  BURST_COOLDOWN_TICKS: 3,
  BURST_COOLDOWN_JITTER: 3,
  BURST_COOLDOWN_SKIP_BOOST: 0.3,
  DREAM_WINDOW_START: 0,
  DREAM_WINDOW_END: 5,
  DREAM_COOLDOWN_HOURS: 20,
  SLEEP_MIN_HOURS: 5,
  SLEEP_MAX_HOURS: 7,
  MID_EVENT_NOTIFY_PROBABILITY: 0.3
} as const

export const HEARTBEAT_GATING = {
  BASE: 0.5,
  ENERGY_WEIGHT: -0.4,
  BOREDOM_WEIGHT: 0.3,
  EXCITEMENT_WEIGHT: -0.3,
  CONNECTION_WEIGHT: -0.2,
  MIN_SKIP: 0.0,
  MAX_SKIP: 0.8
} as const

export const BOREDOM = {
  MIN_BOREDOM: 0.5,
  MIN_IDLE_TICKS: 2,
  BASE_PROBABILITY: 0.3,
  BOREDOM_SCALE: 0.4,
  IDLE_SCALE: 0.1,
  MAX_RECENT_IMPULSES: 10,
  ESCALATION_PERSONAL_TICKS: 5,
  ESCALATION_URGENT_TICKS: 10
} as const

export const HUMOR = {
  QUERY_MIN_EXCITEMENT: 0.5,
  QUERY_MIN_CONNECTION: 0.6,
  MAX_EPISODES_IN_CONTEXT: 3,
  CALLBACK_MIN_SCORE: 0.7,
  CALLBACK_MAX: 2
} as const
