export const HEARTBEAT_GATING = {
  BASE: 0.5,
  ENERGY_WEIGHT: -0.4,
  BOREDOM_WEIGHT: 0.3,
  EXCITEMENT_WEIGHT: -0.3,
  CONNECTION_WEIGHT: -0.2,
  MIN_SKIP: 0.0,
  MAX_SKIP: 0.8
} as const

export const HUMOR = {
  QUERY_MIN_EXCITEMENT: 0.5,
  QUERY_MIN_CONNECTION: 0.6,
  MAX_EPISODES_IN_CONTEXT: 3,
  CALLBACK_MIN_SCORE: 0.7,
  CALLBACK_MAX: 2
} as const
