export const DECEPTION = {
  HIDE_DISSONANCE_THRESHOLD: 0.4,
  HIDE_AUTHENTICITY_THRESHOLD: 0.7,
  HIDE_PROBABILITY_SCALE: 0.3,
  DREAM_DISCOVERY_PROBABILITY: 0.15,
  REFLECTION_DISCOVERY_PROBABILITY: 0.1,
  VULNERABILITY_DISCOVERY_PROBABILITY: 0.05,
  MAX_ACTIVE_DRIVERS: 5
} as const
