export const HEBBIAN = {
  LTP_INCREMENT: 0.02,
  LTD_RATE: 0.001,
  MIN_STRENGTH: 0.01,
  MAX_STRENGTH: 0.95,
  MAX_ASSOCIATIONS: 200,
  ACTIVATION_THRESHOLD: 0.15,
  COACTIVATION_WINDOW_TICKS: 3,
  EXTRACTION_PROBABILITY: 0.3,
  PRUNE_PROBABILITY: 0.02
} as const
