export const DISTORTION = {
  BASE_PROBABILITY: 0.12,
  AGE_SCALE_DAYS: 60,
  MAX_AGE_CONTRIBUTION: 0.3,
  RELEVANCE_WEIGHT: 0.1,
  EMOTION_WEIGHT: 0.05,
  TEMPORAL_SHIFT_MAX_DAYS: 3,
  CONFLATION_MIN_SCORE: 0.6,
  CONFLATION_PROBABILITY: 0.1,
  TYPE_TEMPORAL_CONFUSION: 0.3,
  TYPE_DETAIL_ALTERATION: 0.55,
  TYPE_EMOTIONAL_RECOLORING: 0.75,
  TYPE_SOURCE_CONFUSION: 0.9,
  MIN_SENTENCE_LENGTH: 10
} as const
