export const MIND = {
  CONFIDENCE_DECAY_PER_HOUR: 0.05,
  CORRECTION_CONFIDENCE_PENALTY: 0.1,
  SHORT_MESSAGE_THRESHOLD: 20,
  RAPID_MESSAGE_INTERVAL_MS: 30000,
  LONG_SILENCE_MINUTES: 120
} as const

export const OPERATOR_PROFILE = {
  MAX_MOOD_HISTORY: 10,
  MAX_CORRECTION_PATTERNS: 15,
  PROFILE_UPDATE_COOLDOWN_HOURS: 12
} as const

export const MISCALIBRATION = {
  CORRECTION_DELAY_PROBABILITY: 0.3,
  MAX_DELAY_CYCLES: 2,
  RANDOM_CONFIDENCE_DIP_PROBABILITY: 0.05,
  DIP_MIN: 0.15,
  DIP_MAX: 0.3
} as const

export const RELATIONAL_TRIGGERS = {
  MAX_PATTERNS: 15,
  MIN_MATCH_CONFIDENCE: 0.3,
  MIN_LEARN_CONFIDENCE: 0.4,
  MAX_TRIGGER_INTENSITY: 0.5,
  CONFIDENCE_INTENSITY_SCALE: 0.6,
  CONFIDENCE_PER_OBSERVATION: 0.1,
  SHORT_MESSAGE_THRESHOLD: 25,
  LONG_MESSAGE_THRESHOLD: 120
} as const
